### ISSUE TITLE
Problem installing Petar on cluster

### ISSUE THREAD

**Issue by fredt00** [amusecode/amuse#1026]
Hi, I've been trying to install Petar onto a computing cluster. Other codes have built successfully such as ph4, smalln and Kepler. However, when I tried 

`pip install --no-cache-dir --no-build-isolation --no-clean amuse-petar -v`

in my virtual environment, I get the output:
```
Using pip 23.3.2 from /mnt/zfsusers/fthompson/amuse/amuse-env-test/lib/python3.11/site-packages/pip (python 3.11)
Collecting amuse-petar
  Downloading amuse-petar-2023.11.0.tar.gz (25 kB)
  Running command Preparing metadata (pyproject.toml)
  WARNING setuptools_scm.pyproject_reading toml section missing 'pyproject.toml does not contain a tool.setuptools_scm section'
  running dist_info
  creating /tmp/pip-modern-metadata-ip5_8199/amuse_petar.egg-info
  writing /tmp/pip-modern-metadata-ip5_8199/amuse_petar.egg-info/PKG-INFO
  writing dependency_links to /tmp/pip-modern-metadata-ip5_8199/amuse_petar.egg-info/dependency_links.txt
  writing requirements to /tmp/pip-modern-metadata-ip5_8199/amuse_petar.egg-info/requires.txt
  writing top-level names to /tmp/pip-modern-metadata-ip5_8199/amuse_petar.egg-info/top_level.txt
  writing manifest file '/tmp/pip-modern-metadata-ip5_8199/amuse_petar.egg-info/SOURCES.txt'
  ERROR setuptools_scm._file_finders.git listing git files failed - pretending there aren't any
  reading manifest file '/tmp/pip-modern-metadata-ip5_8199/amuse_petar.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files matching '*.pyc' found under directory 'src'
  warning: no previously-included files matching '*.o' found under directory 'src'
  warning: no previously-included files matching '*~' found under directory 'src'
  warning: no previously-included files matching '.pc' found under directory 'src'
  warning: no previously-included files matching 'ccache' found under directory 'src'
  warning: no previously-included files matching '*.a' found under directory 'src'
  writing manifest file '/tmp/pip-modern-metadata-ip5_8199/amuse_petar.egg-info/SOURCES.txt'
  creating '/tmp/pip-modern-metadata-ip5_8199/amuse_petar-2023.11.0.dist-info'


  In this session you have used the AMUSE modules below.
  Please cite any relevant articles:


        "AMUSE (2023.11.0)"
                DOI:10.5281/zenodo.1435860
                ADS:2018araa.book.....P (Portegies Zwart, S. & McMillan, S.L.W., 2018)
                ADS:2013CoPhC.183..456P ** (Portegies Zwart, S. et al., 2013)
                ADS:2013A&A...557A..84P ** (Pelupessy, F. I. et al., 2013)
                ADS:2009NewA...14..369P (Portegies Zwart, S. et al., 2009)

  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: amuse-framework in /mnt/zfsusers/fthompson/amuse/amuse-env-test/lib/python3.11/site-packages (from amuse-petar) (2023.11.0)
Requirement already satisfied: setuptools>=41.0.0 in /mnt/zfsusers/fthompson/amuse/amuse-env-test/lib/python3.11/site-packages (from amuse-framework->amuse-petar) (65.5.0)
Requirement already satisfied: setuptools-scm in /mnt/zfsusers/fthompson/amuse/amuse-env-test/lib/python3.11/site-packages (from amuse-framework->amuse-petar) (8.0.4)
Requirement already satisfied: pip>=19.0.0 in /mnt/zfsusers/fthompson/amuse/amuse-env-test/lib/python3.11/site-packages (from amuse-framework->amuse-petar) (23.3.2)
Requirement already satisfied: wheel>=0.32 in /mnt/zfsusers/fthompson/amuse/amuse-env-test/lib/python3.11/site-packages (from amuse-framework->amuse-petar) (0.42.0)
Requirement already satisfied: docutils>=0.6 in /mnt/zfsusers/fthompson/amuse/amuse-env-test/lib/python3.11/site-packages (from amuse-framework->amuse-petar) (0.20.1)
Requirement already satisfied: numpy>=1.2.2 in /mnt/zfsusers/fthompson/amuse/amuse-env-test/lib/python3.11/site-packages (from amuse-framework->amuse-petar) (1.26.2)
Requirement already satisfied: pytest>=4.0 in /mnt/zfsusers/fthompson/amuse/amuse-env-test/lib/python3.11/site-packages (from amuse-framework->amuse-petar) (7.4.3)
Requirement already satisfied: h5py>=1.1.0 in /mnt/zfsusers/fthompson/amuse/amuse-env-test/lib/python3.11/site-packages (from amuse-framework->amuse-petar) (3.10.0)
Requirement already satisfied: iniconfig in /mnt/zfsusers/fthompson/amuse/amuse-env-test/lib/python3.11/site-packages (from pytest>=4.0->amuse-framework->amuse-petar) (2.0.0)
Requirement already satisfied: packaging in /mnt/zfsusers/fthompson/amuse/amuse-env-test/lib/python3.11/site-packages (from pytest>=4.0->amuse-framework->amuse-petar) (23.2)
Requirement already satisfied: pluggy<2.0,>=0.12 in /mnt/zfsusers/fthompson/amuse/amuse-env-test/lib/python3.11/site-packages (from pytest>=4.0->amuse-framework->amuse-petar) (1.3.0)
Requirement already satisfied: typing-extensions in /mnt/zfsusers/fthompson/amuse/amuse-env-test/lib/python3.11/site-packages (from setuptools-scm->amuse-framework->amuse-petar) (4.8.0)
Building wheels for collected packages: amuse-petar
  Running command Building wheel for amuse-petar (pyproject.toml)
  WARNING setuptools_scm.pyproject_reading toml section missing 'pyproject.toml does not contain a tool.setuptools_scm section'
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/amuse
  creating build/lib/amuse/community
  creating build/lib/amuse/community/petar
  copying src/amuse/community/petar/__init__.py -> build/lib/amuse/community/petar
  copying src/amuse/community/petar/_version.py -> build/lib/amuse/community/petar
  copying src/amuse/community/petar/download.py -> build/lib/amuse/community/petar
  copying src/amuse/community/petar/interface.py -> build/lib/amuse/community/petar
  running build_codes
  building libraries and community codes
  build, for logging, see 'build.log'
  creating build/temp.linux-x86_64-cpython-311
  creating build/temp.linux-x86_64-cpython-311/codes
  creating build/temp.linux-x86_64-cpython-311/codes/petar
  copying src/amuse/community/petar/Makefile -> build/temp.linux-x86_64-cpython-311/codes/petar
  copying src/amuse/community/petar/__init__.py -> build/temp.linux-x86_64-cpython-311/codes/petar
  copying src/amuse/community/petar/_version.py -> build/temp.linux-x86_64-cpython-311/codes/petar
  copying src/amuse/community/petar/download.py -> build/temp.linux-x86_64-cpython-311/codes/petar
  copying src/amuse/community/petar/interface.cc -> build/temp.linux-x86_64-cpython-311/codes/petar
  copying src/amuse/community/petar/interface.h -> build/temp.linux-x86_64-cpython-311/codes/petar
  copying src/amuse/community/petar/interface.py -> build/temp.linux-x86_64-cpython-311/codes/petar
  [18:50:07] building petar
  error in call, tail output:

   26850K .......... .......... .......... .......... ..........  105M
   26900K .......... .......... .......... .......... ..........  118M
   26950K .......... .......... .......... .......... ..........  123M
   27000K .......... .......... .......... .......... .......... 98.9M
   27050K .......... .......... .......... .......... .......... 61.0M
   27100K .......... .......... .......... .......... .......... 93.2M
   27150K .......... .......... .......... .......... .......... 88.6M
   27200K .......... .......... .......... .......... ..........  130M
   27250K .......... .......... .......... .......... ..........  118M
   27300K .......... .......... .......... .......... ..........  126M
   27350K .......... .......... .......... .......... .......... 97.3M
   27400K .......... .......... .......... .......... ..........  113M
   27450K .......... .......... .......... .......... ..........  131M
   27500K .......... .......... .......... .......... .......... 87.5M
   27550K .......... .......... .......... .......... ..........  130M
   27600K .......... .......... .......... .......... ..........  129M
   27650K .......... .......... .......... .......... .......... 98.7M
   27700K .......... .......... .......... .......... .......... 41.5M
   27750K .......... .......... .......... .......... .......... 43.5M
   27800K .......... .......... .......... .......... .......... 5.71M
   27850K .......... .......... .......... .......... .......... 4.87M
   27900K .......... .......... .......... .......... .......... 6.02M
   27950K .......... .......... .......... .......... .......... 5.41M
   28000K .......... .......... .......... .......... .......... 5.33M
   28050K .......... .......... .......... .......... .......... 4.71M
   28100K .......... .......... .......... .......... .......... 56.1M
   28150K .......... .......... .......... .......... .......... 5.42M
   28200K .......... .......... .......... .......... .......... 6.02M
   28250K .......... .......... .......... .......... .......... 5.65M
   28300K .......... .......... .......... .......... .......... 4.16M
   28350K .......... .......... .......... .......... .......... 8.86M
   28400K .......... .......... .......... .......... .......... 44.8M
   28450K .......... .......... .......... .......... .......... 5.06M
   28500K .......... .......... .......... .......... .......... 5.37M
   28550K .......... .......... .......... .......... .......... 5.75M
   28600K .......... .......... .......... .......... .......... 5.71M
   28650K .......... .......... .......... .......... .......... 3.82M
   28700K .......... .......... .......... .......... .......... 57.0M
   28750K .......... .......... .......... .......... .......... 4.83M
   28800K .......... .......... .......... .......... .......... 6.11M
   28850K .......... .......... .......... .......... .......... 5.34M
   28900K .......... .......... .......... .......... .......... 4.02M
   28950K .......... .......... .......... .......... .......... 8.46M
   29000K .......... .......... .......... .......... .......... 74.2M
   29050K .......... .......... .......... .......... .......... 4.99M
   29100K .......... .......... .......... .......... .......... 4.08M
   29150K .......... .......... .......... .......... .......... 6.37M
   29200K .......... .......... .......... .......... .......... 6.73M
   29250K .......... .......... .......... .......... .......... 5.66M
   29300K .......... .......... .......... .......... .......... 5.63M
   29350K .......... .......... .......... .......... .......... 65.7M
   29400K .......... .......... .......... .......... .......... 4.04M
   29450K .......... .......... .......... .......... .......... 6.08M
   29500K .......... .......... .......... .......... .......... 6.40M
   29550K .......... .......... .......... .......... .......... 5.52M
   29600K .......... .......... .......... .......... .......... 5.58M
   29650K .......... .......... .......... .......... .......... 50.7M
   29700K .......... .......... .......... .......... .......... 6.68M
   29750K .......... .......... .......... .......... .......... 3.53M
   29800K .......... .......... .......... .......               13.0M=1.5s

  2024-01-17 18:50:12 (19.1 MB/s) - ‘55b2bafd316805bad22057cf4ee96217735279bf.tar.gz’ saved [30553099]

  downloading version 6ccac364e83ab05e4dad27e6eb6abdf7e5c89bcc from https://github.com/lwang-astro/PeTar/archive/6ccac364e83ab05e4dad27e6eb6abdf7e5c89bcc.tar.gz to 6ccac364e83ab05e4dad27e6eb6abdf7e5c89bcc.tar.gz
  downloading finished
  unpacking 6ccac364e83ab05e4dad27e6eb6abdf7e5c89bcc.tar.gz
  done
  downloading version a4ff4b3d076535684313a912ea31985c1431f827 from https://github.com/lwang-astro/SDAR/archive/a4ff4b3d076535684313a912ea31985c1431f827.tar.gz to a4ff4b3d076535684313a912ea31985c1431f827.tar.gz
  downloading finished
  unpacking a4ff4b3d076535684313a912ea31985c1431f827.tar.gz
  done
  downloading version 55b2bafd316805bad22057cf4ee96217735279bf from https://github.com/FDPS/FDPS/archive/55b2bafd316805bad22057cf4ee96217735279bf.tar.gz to 55b2bafd316805bad22057cf4ee96217735279bf.tar.gz
  downloading finished
  unpacking 55b2bafd316805bad22057cf4ee96217735279bf.tar.gz
  done
  sed 's/@VERSION@/'`cat src/PeTar/VERSION`'_'`cat src/SDAR/VERSION`'/g' src/PeTar/src/get_version.hpp.in >src/PeTar/src/get_version.hpp
  mpicxx /usr/local/shared/python/3.11.4//include -I src/PeTar/src -I src/SDAR/src -I src/FDPS/src  -fPIC -O2 -Wall -std=c++17  -fopenmp -D PARTICLE_SIMULATOR_THREAD_PARALLEL  -D PARTICLE_SIMULATOR_MPI_PARALLEL -D MPICH_IGNORE_CXX_SEEKC -D SOFT_PERT -D AR_TTL -D AR_SLOWDOWN_TREE -D AR_SLOWDOWN_TIMESCALE -D CLUSTER_VELOCITY -D USE_QUAD -D STELLAR_EVOLUTION -D PROFILE -D HARD_CHECK_ENERGY -D TIDAL_TENSOR_3RD -D INTERFACE_DEBUG_PRINT -D INTERFACE_DEBUG -I/mnt/zfsusers/fthompson/amuse/clonedRepo/amuse/lib/stopcond -c -o interface.o interface.cc
  In file included from src/PeTar/src/hard.hpp:17:0,
                   from src/PeTar/src/petar.hpp:72,
                   from interface.cc:1:
  src/PeTar/src/ar_interaction.hpp: In member function ‘int ARInteraction::modifyAndInterruptIter(AR::InterruptBinary<PtclHard>&, AR::BinaryTree<PtclHard>&)’:
  src/PeTar/src/ar_interaction.hpp:774:19: warning: unused variable ‘drdv’ [-Wunused-variable]
               Float drdv = pos_red * vel_red;
                     ^~~~
  g++: warning: /usr/local/shared/python/3.11.4//include: linker input file unused because linking not done
  mpicxx /usr/local/shared/python/3.11.4//include -I src/PeTar/src -I src/SDAR/src -I src/FDPS/src  -fPIC -O2 -Wall -std=c++17  -fopenmp -D PARTICLE_SIMULATOR_THREAD_PARALLEL  -D PARTICLE_SIMULATOR_MPI_PARALLEL -D MPICH_IGNORE_CXX_SEEKC -D SOFT_PERT -D AR_TTL -D AR_SLOWDOWN_TREE -D AR_SLOWDOWN_TIMESCALE -D CLUSTER_VELOCITY -D USE_QUAD -D STELLAR_EVOLUTION -D PROFILE -D HARD_CHECK_ENERGY -D TIDAL_TENSOR_3RD -D INTERFACE_DEBUG_PRINT -D INTERFACE_DEBUG -I/mnt/zfsusers/fthompson/amuse/clonedRepo/amuse/lib/stopcond   -lm  worker_code.cc interface.o   -o petar_worker -L/mnt/zfsusers/fthompson/amuse/clonedRepo/amuse/lib/stopcond -lstopcondmpi
  worker_code.cc:60:13: warning: ‘FALSE_BYTE’ defined but not used [-Wunused-variable]
   static bool FALSE_BYTE = 0;
               ^~~~~~~~~~
  worker_code.cc:59:13: warning: ‘TRUE_BYTE’ defined but not used [-Wunused-variable]
   static bool TRUE_BYTE = 1;
               ^~~~~~~~~
  worker_code.cc:28:13: warning: ‘NEEDS_MPI’ defined but not used [-Wunused-variable]
   static bool NEEDS_MPI = true;
               ^~~~~~~~~
  /usr/bin/ld: cannot find /usr/local/shared/python/3.11.4//include: File format not recognized
  collect2: error: ld returned 1 exit status
  Makefile:85: recipe for target 'petar_worker' failed
  make: *** [petar_worker] Error 1
  make: Leaving directory '/tmp/pip-install-i7cyy57g/amuse-petar_c86893928e474b5193cd93452d3f2ca1/build/temp.linux-x86_64-cpython-311/codes/petar'

  --------------------------------------------------------------------------------
  will copy worker: src/amuse/community/petar
  petar
  Community codes not built (because of errors/ missing libraries):
  ================================================================================
   * petar
  ================================================================================
  0 out of 1 codes built, 0 out of 0 libraries built
  Traceback (most recent call last):
    File "/mnt/zfsusers/fthompson/amuse/amuse-env-test/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/mnt/zfsusers/fthompson/amuse/amuse-env-test/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/mnt/zfsusers/fthompson/amuse/amuse-env-test/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/mnt/zfsusers/fthompson/amuse/amuse-env-test/lib/python3.11/site-packages/setuptools/build_meta.py", line 412, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/mnt/zfsusers/fthompson/amuse/amuse-env-test/lib/python3.11/site-packages/setuptools/build_meta.py", line 397, in _build_with_temp_dir
      self.run_setup()
    File "/mnt/zfsusers/fthompson/amuse/amuse-env-test/lib/python3.11/site-packages/setuptools/build_meta.py", line 484, in run_setup
      self).run_setup(setup_script=setup_script)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/mnt/zfsusers/fthompson/amuse/amuse-env-test/lib/python3.11/site-packages/setuptools/build_meta.py", line 335, in run_setup
      exec(code, locals())
    File "<string>", line 43, in <module>
    File "/mnt/zfsusers/fthompson/amuse/amuse-env-test/lib/python3.11/site-packages/setuptools/__init__.py", line 87, in setup
      return distutils.core.setup(**attrs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/mnt/zfsusers/fthompson/amuse/amuse-env-test/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
      return run_commands(dist)
             ^^^^^^^^^^^^^^^^^^
    File "/mnt/zfsusers/fthompson/amuse/amuse-env-test/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
      dist.run_commands()
    File "/mnt/zfsusers/fthompson/amuse/amuse-env-test/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
      self.run_command(cmd)
    File "/mnt/zfsusers/fthompson/amuse/amuse-env-test/lib/python3.11/site-packages/setuptools/dist.py", line 1217, in run_command
      super().run_command(command)
    File "/mnt/zfsusers/fthompson/amuse/amuse-env-test/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
      cmd_obj.run()
    File "/mnt/zfsusers/fthompson/amuse/amuse-env-test/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 368, in run
      self.run_command("build")
    File "/mnt/zfsusers/fthompson/amuse/amuse-env-test/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
      self.distribution.run_command(command)
    File "/mnt/zfsusers/fthompson/amuse/amuse-env-test/lib/python3.11/site-packages/setuptools/dist.py", line 1217, in run_command
      super().run_command(command)
    File "/mnt/zfsusers/fthompson/amuse/amuse-env-test/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
      cmd_obj.run()
    File "/mnt/zfsusers/fthompson/amuse/amuse-env-test/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 132, in run
      self.run_command(cmd_name)
    File "/mnt/zfsusers/fthompson/amuse/amuse-env-test/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
      self.distribution.run_command(command)
    File "/mnt/zfsusers/fthompson/amuse/amuse-env-test/lib/python3.11/site-packages/setuptools/dist.py", line 1217, in run_command
      super().run_command(command)
    File "/mnt/zfsusers/fthompson/amuse/amuse-env-test/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-i7cyy57g/amuse-petar_c86893928e474b5193cd93452d3f2ca1/support/setup_codes.py", line 1101, in run
      raise Exception("No succesful builds detected. Aborting.")
  Exception: No succesful builds detected. Aborting.
  error: subprocess-exited-with-error
  
  × Building wheel for amuse-petar (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /mnt/zfsusers/fthompson/amuse/amuse-env-test/bin/python3 /mnt/zfsusers/fthompson/amuse/amuse-env-test/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py build_wheel /tmp/tmpq6sstx49
  cwd: /tmp/pip-install-i7cyy57g/amuse-petar_c86893928e474b5193cd93452d3f2ca1
  Building wheel for amuse-petar (pyproject.toml) ... error
  ERROR: Failed building wheel for amuse-petar
Failed to build amuse-petar
ERROR: Could not build wheels for amuse-petar, which is required to install pyproject.toml-based projects
```

I tried to clone the repository and then:
pip install -e .
make framework
make petar.code

but this also failed with the same message. Here are my config.mk and build.log files: 
[build.log](https://github.com/amusecode/amuse/files/13967491/build.log)
[config.mk.txt](https://github.com/amusecode/amuse/files/13967500/config.mk.txt)

I'd really appreciate any suggestions.
Best,
Fred

**Comment by spzwart** [comment]
You have to install petar from source,  it is not pip-able, in part due to
the gpu requirements.

good luck,
Simon

**Comment by fredt00** [comment]
Hi Simon,

Thanks for the quick reply. I did manage to install amuse-petar via pip on my laptop and it seems to run correctly, so I was hoping this would also be possible on a cluster.

Fred

**Comment by rieder** [comment]
Installing PeTar via pip is possible - but as Simon said, not with GPU support.
From the error you get it looks to me like there's an error with your Python environment:
`/usr/bin/ld: cannot find /usr/local/shared/python/3.11.4//include: File format not recognized`
Are you indeed using Python 3.11.4? Have you loaded the right module for this? If so, could you check this directory?

**Comment by LourensVeen** [comment]
I bet if you did `echo ${CXXFLAGS}` it would show that `/usr/local/shared/python/3.11.4//include`. That's not a valid C++ compiler flag, so the compiler rejects it and the build fails.

How did you make Python 3.11 available? If it's through a module then that module is probably broken in that it doesn't set the environment correctly...

**Comment by fredt00** [comment]
I loaded the module python3.11.4 to create the virtual environment. Checking the directory gives:

/usr/local/shared/python/3.11.4/include/python3.11$ ls
abstract.h         datetime.h             frameobject.h         methodobject.h  pycapsule.h    pymacro.h    pytypedefs.h    tupleobject.h
bltinmodule.h      descrobject.h          genericaliasobject.h  modsupport.h    pyconfig.h     pymath.h     rangeobject.h   typeslots.h
boolobject.h       dictobject.h           import.h              moduleobject.h  py_curses.h    pymem.h      setobject.h     unicodeobject.h
bytearrayobject.h  dynamic_annotations.h  internal              object.h        pydtrace.h     pyport.h     sliceobject.h   warnings.h
bytesobject.h      enumobject.h           intrcheck.h           objimpl.h       pyerrors.h     pystate.h    structmember.h  weakrefobject.h
ceval.h            errcode.h              iterobject.h          opcode.h        pyexpat.h      pystrcmp.h   structseq.h
codecs.h           exports.h              listobject.h          osdefs.h        pyframe.h      pystrtod.h   sysmodule.h
compile.h          fileobject.h           longobject.h          osmodule.h      pyhash.h       Python.h     token.h
complexobject.h    fileutils.h            marshal.h             patchlevel.h    pylifecycle.h  pythonrun.h  traceback.h
cpython            floatobject.h          memoryobject.h        pybuffer.h      pymacconfig.h  pythread.h   tracemalloc.h


so it looks like the python directory is correct. When I type echo ${CXXFLAGS} into the terminal nothing is returned.

**Comment by fredt00** [comment]
Yes, echo $INCLUDE does return /usr/local/shared/python/3.11.4//include, but echo $MPICXX also returns nothing.

**Comment by LourensVeen** [comment]
Ah, that would be the issue then. It seems like the PeTaR Makefile and whatever set that `INCLUDE` variable disagree on the required syntax. I'm not sure who's right, but `unset INCLUDE` or `export INCLUDE=` and then compiling again should fix at least this error.

**Comment by fredt00** [comment]
That solved the problem! Petar now builds and runs successfully. Thanks for the help!

**Comment by LourensVeen** [comment]
You're welcome! I'll close this issue now, please open a new one if you run into any other issues.
