### ISSUE TITLE
help(gravity.parameters) raises exception

### ISSUE THREAD

**Issue by LourensVeen** [amusecode/amuse#1089]
**Describe the bug**
The book says to use `help(gravity.parameters)` to show help for the parameters of a gravity code. If I do that (with Python 3.13, but I'm not sure that that's relevant), I get an exception instead of help.

**To Reproduce**
```
from amuse.community.brutus import Brutus
b = Brutus()
help(b.parameters)

Traceback (most recent call last):
  File "<python-input-3>", line 1, in <module>
    help(b.parameters)
    ~~~~^^^^^^^^^^^^^^
  File "<frozen _sitebuiltins>", line 103, in __call__
  File "/home/lourens/.miniconda3/envs/amuse-mpreal/lib/python3.13/pydoc.py", line 1992, in __call__
    self.help(request)
    ~~~~~~~~~^^^^^^^^^
  File "/home/lourens/.miniconda3/envs/amuse-mpreal/lib/python3.13/pydoc.py", line 2053, in help
    else: doc(request, 'Help on %s:', output=self._output, is_cli=is_cli)
          ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lourens/.miniconda3/envs/amuse-mpreal/lib/python3.13/pydoc.py", line 1759, in doc
    what = getattr(thing, '__qualname__', None)
  File "/home/lourens/NLeSC/projects/ReDiTSAp/software/amuse_lourens/src/amuse/datamodel/parameters.py", line 38, in __getattr__
    raise exceptions.CoreException(
    ...<2 lines>...
    )
amuse.support.exceptions.CoreException: tried to get unknown parameter '__qualname__' for a 'Brutus' object
```

**Expected behavior**
A clear and concise description of which parameters exist and what they mean.

**Environment (please complete the following information):**
 - OS and version: Kubuntu 22.04
 - Compiler: N/A

**Additional context**
Looking at `parameters.py:35`, there's two commented-out lines that seem like they could solve the problem, and indeed it works if I enable them again. Unfortunately there's no comment to explain why they're commented out, so I'm not sure if that breaks something else.

**Comment by rieder** [comment]
Specific for Brutus? Or also other community codes?
We should probably make a unittest for this.
