### ISSUE TITLE
Unexpected behaviour new_fractal_cluster_model

### ISSUE THREAD

**Issue by iambernie** [amusecode/amuse#23]
This issue may (or may not) be related to #7 .

The following piece of code `generate_fractals.py` crashes after 1089 models.

```python
#generate_fractals.py
import numpy
from amuse.ic.fractalcluster import new_fractal_cluster_model
from amuse.ic.salpeter import new_salpeter_mass_distribution
from amuse.units import units
from amuse.units.nbody_system import nbody_to_si

numpy.random.seed(123)
masses = new_salpeter_mass_distribution(100)

models = []

theta_true = [2, 1.6]
guesses = 0.3 * numpy.random.randn(2000*2).reshape(2000, 2) + theta_true

for i in range(2000):
    vradius, fdim = guesses[i]
    print(i, vradius, fdim)
    converter = nbody_to_si(masses.sum(), vradius |units.parsec)
    models.append(new_fractal_cluster_model(convert_nbody=converter,
                                            N=100,
                                            masses=masses,
                                            fractal_dimension=fdim,
                                            virial_ratio=0.0,
                                            random_seed=i, 
                                            match_N=True))
```

```
bernie @ archbox: ~/githubs/fractalsproject/tests (master)% time am generate_fractals.py
(0, 2.6261340078764555, 1.6493323690689476)
(1, 2.3450616627639898, 1.219794385296932)
(2, 2.054310538879101, 1.9533585816425736)
(3, 1.8994967714200952, 1.9093343376765228)
[...]
(1087, 2.4213385288873868, 1.6016495030916851)
(1088, 1.6922299795081461, 1.6144512470492853)
(1089, 1.9724433265007539, 1.3019379430875744)
Traceback (most recent call last):
  File "generate_fractals.py", line 30, in <module>
    match_N=True))
  File "/home/bernie/githubs/amuse/src/amuse/community/fractalcluster/interface.py", line 276, in new_fractal_cluster_model
    return uc.result
  File "/home/bernie/githubs/amuse/src/amuse/community/fractalcluster/interface.py", line 254, in result
    particles = self.new_model()
  File "/home/bernie/githubs/amuse/src/amuse/community/fractalcluster/interface.py", line 242, in new_model
    generator.generate_particles()
  File "/home/bernie/githubs/amuse/src/amuse/community/fractalcluster/interface.py", line 189, in generate_particles
    result = self.overridden().generate_particles()
  File "/home/bernie/githubs/amuse/src/amuse/support/methods.py", line 107, in __call__
    result = self.method(*list_arguments, **keyword_arguments)
  File "/home/bernie/githubs/amuse/src/amuse/support/methods.py", line 107, in __call__
    result = self.method(*list_arguments, **keyword_arguments)
  File "/home/bernie/githubs/amuse/src/amuse/support/methods.py", line 196, in __call__
    return self.method(*list_arguments, **keyword_arguments)
  File "/home/bernie/githubs/amuse/src/amuse/rfi/core.py", line 113, in __call__
    raise exceptions.CodeException("Exception when calling function '{0}', of code '{1}', exception was '{2}'".format(self.specification.name, type(self.interface).__name__, ex))
amuse.support.exceptions.CodeException: Exception when calling function 'generate_particles', of code 'FractalClusterInterface', exception was 'lost connection to code'
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[13870,1],0]
  Exit code:    245
--------------------------------------------------------------------------
am generate_fractals.py  152.41s user 38.36s system 43% cpu 7:17.60 total
bernie @ archbox: ~/githubs/fractalsproject/tests (master)%
```

I've ran this multiple times, and it always crashes at the same seed.

Btw, one can speed up to the point where it crashes by wrapping the `new_fractal_cluster_model`
call into an `if == 1089` block.

``` python
if i == 1089:
    models.append(new_fractal_cluster_model(convert_nbody=converter,
                                            N=100,
                                            masses=masses,
                                            fractal_dimension=fdim,
                                            virial_ratio=0.0,
                                            random_seed=i,
                                            match_N=True))
```

**Comment by ipelupessy** [comment]
if I remember correctly this one was resolved
