### ISSUE TITLE
test_python_implementation test26 & test27 fail for Python 3 / mpi4py 3.0.0

### ISSUE THREAD

**Issue by evertrol** [amusecode/amuse#249]
When running the unit tests, `test26` and `test27` in `amuse/test/suite/codes_tests/test_python_implementation` fails. 

This is for Python 3.6 (possibly Python 2 as well) and mpi4py 3.0.0 (most recent version).

Running this as 
```
mpiexec /usr/local/bin/python3.6 -m nose /usr/local/lib/python3.6/site-packages/amuse/test/suite/codes_tests/test_python_implementation.py -m 'test2[67]'
```

The full traceback is listed at the end.

This is on MacOSX 10.13.5, Homebrew Python 3.6, Homebrew mpich (compiled with Homebrew gcc-8), mpi4py 3.0.0.

mpi4py version 1 and 2 do not show an error.

---

(Separated the two tests, because nose intertwines some of the output. The errors are not identical, but possibly related.)

Traceback for test26:
```
mpiexec /usr/local/bin/python3.6 -m nose /usr/local/lib/python3.6/site-packages/amuse/test/suite/codes_tests/test_python_implementation.py -m 'test26'
E
======================================================================
ERROR: test26 (amuse.test.suite.codes_tests.test_python_implementation.TestInterface)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/amuse/test/suite/codes_tests/test_python_implementation.py", line 886, in test26
    portname, error = instance1.internal__open_port()
  File "/usr/local/lib/python3.6/site-packages/amuse/rfi/core.py", line 115, in __call__
    raise exceptions.CodeException("Exception when calling function '{0}', of code '{1}', exception was '{2}'".format(self.specification.name, type(self.interface).__name__, ex))
amuse.support.exceptions.CodeException: Exception when calling function 'internal__open_port', of code 'ForTestingInterface', exception was 'Error in code: Argument 'info' has incorrect type (expected mpi4py.MPI.Info, got NoneType)'
-------------------- >> begin captured logging << --------------------
amuse.rfi.channel: DEBUG: got 1 strings of size [75]
amuse.rfi.channel: DEBUG: got 1 strings of size [75], data = ["Argument 'info' has incorrect type (expected mpi4py.MPI.Info, got NoneType)"]
amuse.rfi.channel: INFO: error message!
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 0.585s

FAILED (errors=1)
```

Traceback for test27:
```
mpiexec /usr/local/bin/python3.6 -m nose /usr/local/lib/python3.6/site-packages/amuse/test/suite/codes_tests/test_python_implementation.py -m 'test27'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/amuse/rfi/python_code.py", line 182, in handle_message
    result = method(**keyword_arguments)
TypeError: internal__open_port() got an unexpected keyword argument 'port_identifier'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/amuse/rfi/python_code.py", line 81, in start
    self.handle_message(message, result_message)
  File "/usr/local/lib/python3.6/site-packages/amuse/rfi/python_code.py", line 186, in handle_message
    result = method(*list(keyword_arguments))
  File "/usr/local/lib/python3.6/site-packages/amuse/rfi/python_code.py", line 313, in internal__open_port
    outportname.value = MPI.Open_port(None)
TypeError: Argument 'info' has incorrect type (expected mpi4py.MPI.Info, got NoneType)
Argument 'info' has incorrect type (expected mpi4py.MPI.Info, got NoneType)
E
======================================================================
ERROR: test27 (amuse.test.suite.codes_tests.test_python_implementation.TestInterface)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/amuse/test/suite/codes_tests/test_python_implementation.py", line 912, in test27
    portname, error = instance2.internal__open_port()
  File "/usr/local/lib/python3.6/site-packages/amuse/rfi/core.py", line 115, in __call__
    raise exceptions.CodeException("Exception when calling function '{0}', of code '{1}', exception was '{2}'".format(self.specification.name, type(self.interface).__name__, ex))
amuse.support.exceptions.CodeException: Exception when calling function 'internal__open_port', of code 'ForTestingInterface', exception was 'Error in code: Argument 'info' has incorrect type (expected mpi4py.MPI.Info, got NoneType)'
-------------------- >> begin captured stdout << ---------------------
<class 'amuse.test.suite.codes_tests.test_python_implementation.ForTestingInterface'>

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
amuse.rfi.channel: DEBUG: got 1 strings of size [75]
amuse.rfi.channel: DEBUG: got 1 strings of size [75], data = ["Argument 'info' has incorrect type (expected mpi4py.MPI.Info, got NoneType)"]
amuse.rfi.channel: INFO: error message!
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 0.523s

FAILED (errors=1)
```

**Comment by evertrol** [comment]
Below are the errors I get with Python 2 & mpi4py 3.0.0.
This time, test 27 does not show the `unexpected keyword argument 'port_identifier'` error, but I don't know enough about the code and MPI to know how relevant that is.

---
# test26
```
$ mpiexec python2.7 -m nose /usr/local/lib/python2.7/site-packages/amuse/test/suite/codes_tests/test_python_implementation.py -m test26
E
======================================================================
ERROR: test26 (amuse.test.suite.codes_tests.test_python_implementation.TestInterface)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/amuse/test/suite/codes_tests/test_python_implementation.py", line 886, in test26
    portname, error = instance1.internal__open_port()
  File "/usr/local/lib/python2.7/site-packages/amuse/rfi/core.py", line 115, in __call__
    raise exceptions.CodeException("Exception when calling function '{0}', of code '{1}', exception was '{2}'".format(self.specification.name, type(self.interface).__name__, ex))
CodeException: Exception when calling function 'internal__open_port', of code 'ForTestingInterface', exception was 'Error in code: Argument 'info' has incorrect type (expected mpi4py.MPI.Info, got NoneType)'
-------------------- >> begin captured logging << --------------------
amuse.rfi.channel: DEBUG: got 1 strings of size [75]
amuse.rfi.channel: DEBUG: got 1 strings of size [75], data = [u"Argument 'info' has incorrect type (expected mpi4py.MPI.Info, got NoneType)"]
amuse.rfi.channel: INFO: error message!
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 0.554s

FAILED (errors=1)
```

# test27
```
$ mpiexec python2.7 -m nose /usr/local/lib/python2.7/site-packages/amuse/test/suite/codes_tests/test_python_implementation.py -m test27
Argument 'info' has incorrect type (expected mpi4py.MPI.Info, got NoneType)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/amuse/rfi/python_code.py", line 81, in start
    self.handle_message(message, result_message)
  File "/usr/local/lib/python2.7/site-packages/amuse/rfi/python_code.py", line 185, in handle_message
    result = method(*list(keyword_arguments))
  File "/usr/local/lib/python2.7/site-packages/amuse/rfi/python_code.py", line 312, in internal__open_port
    outportname.value = MPI.Open_port(None)
TypeError: Argument 'info' has incorrect type (expected mpi4py.MPI.Info, got NoneType)
E
======================================================================
ERROR: test27 (amuse.test.suite.codes_tests.test_python_implementation.TestInterface)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/amuse/test/suite/codes_tests/test_python_implementation.py", line 912, in test27
    portname, error = instance2.internal__open_port()
  File "/usr/local/lib/python2.7/site-packages/amuse/rfi/core.py", line 115, in __call__
    raise exceptions.CodeException("Exception when calling function '{0}', of code '{1}', exception was '{2}'".format(self.specification.name, type(self.interface).__name__, ex))
CodeException: Exception when calling function 'internal__open_port', of code 'ForTestingInterface', exception was 'Error in code: Argument 'info' has incorrect type (expected mpi4py.MPI.Info, got NoneType)'
-------------------- >> begin captured stdout << ---------------------
<class 'amuse.test.suite.codes_tests.test_python_implementation.ForTestingInterface'>

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
amuse.rfi.channel: DEBUG: got 1 strings of size [75]
amuse.rfi.channel: DEBUG: got 1 strings of size [75], data = [u"Argument 'info' has incorrect type (expected mpi4py.MPI.Info, got NoneType)"]
amuse.rfi.channel: INFO: error message!
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 0.497s

FAILED (errors=1)
```

**Comment by ipelupessy** [comment]
this is not python 3 specfic...

**Comment by ipelupessy** [comment]
works here
