### ISSUE TITLE
mpi4py or openmpi issues on Ubuntu 12.04

### ISSUE THREAD

**Issue by iambernie** [amusecode/amuse#26]
I'm having some issues with OpenMPI (or mpi4py?) on a machine running Ubuntu 12.04 Precise Pangolin and I'm not sure whether I'm doing something wrong or whether this is a bug.

Here is some information about the machine:
```
laub @ u0007221: ~% uname -a 
Linux u0007221 3.13.0-73-generic #116~precise1-Ubuntu SMP Sun Dec 6 16:55:45 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

laub @ u0007221: ~% dpkg -l | grep openmpi | column -t
ii  libopenmpi-dev      1.4.3-2.1ubuntu3  high  performance  message  passing  library  --  header      files
ii  libopenmpi1.3       1.4.3-2.1ubuntu3  high  performance  message  passing  library  --  shared      library
ii  openmpi-bin         1.4.3-2.1ubuntu3  high  performance  message  passing  library  --  binaries
ii  openmpi-checkpoint  1.4.3-2.1ubuntu3  high  performance  message  passing  library  --  checkpoint  support
ii  openmpi-common      1.4.3-2.1ubuntu3  high  performance  message  passing  library  --  common      files

laub @ u0007221: ~% mpicxx -v                        
Using built-in specs.
COLLECT_GCC=/usr/bin/g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.6/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 4.6.3-1ubuntu5' --with-bugurl=file:///usr/share/doc/gcc-4.6/README.Bugs --enable-languages=c,c++,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.6 --enable-shared --enable-linker-build-id --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.6 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --enable-plugin --enable-objc-gc --disable-werror --with-arch-32=i686 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5) 
```

Every piece of code I've tried to run so far raises the following AttributeError.
```
laub @ u0007221: /scratch/laub/amuse/examples/simple (master)% am sunandearth.py
Traceback (most recent call last):
  File "sunandearth.py", line 80, in <module>
    x,y = simulate_system_until(particles, 20 | units.yr)
  File "sunandearth.py", line 34, in simulate_system_until
    instance = Hermite(convert_nbody)
  File "/scratch/laub/amuse/src/amuse/community/hermite0/interface.py", line 208, in __init__
    legacy_interface = HermiteInterface(**options)
  File "/scratch/laub/amuse/src/amuse/community/hermite0/interface.py", line 25, in __init__
    **options)
  File "/scratch/laub/amuse/src/amuse/rfi/core.py", line 704, in __init__
    self._start(name_of_the_worker = name_of_the_worker, **options)
  File "/scratch/laub/amuse/src/amuse/rfi/core.py", line 714, in _start
    self.channel = self.channel_factory(name_of_the_worker, type(self), interpreter_executable = interpreter_executable, **options)
  File "/scratch/laub/amuse/src/amuse/rfi/channel.py", line 1155, in __init__
    self.ensure_mpi_initialized()
  File "/scratch/laub/amuse/src/amuse/rfi/channel.py", line 1188, in ensure_mpi_initialized
    if rc.threaded:
AttributeError: 'function' object has no attribute 'threaded'
```

Running the above example with `mpiexec am sunandearth.py` results in the same output.

**Comment by iambernie** [comment]
So it looks like the variable `rc.threaded` was renamed at some [point](https://bitbucket.org/mpi4py/mpi4py/commits/edca4fc223dd285eea7c4228044cc1cd36c33225#chg-src/__init__.py) to `rc.threads`, and that version 2.0.0 of mpi4py (which I'm apparently currently running) does not support the old variable `rc.threaded`.

**Comment by iambernie** [comment]
I have made PR #27 for this issue.
