### ISSUE TITLE
Pip install amuse-(code) fails on Linux (Ubuntu) system

### ISSUE THREAD

**Issue by rieder** [amusecode/amuse#406]
**Describe the bug**
Installing a community code (e.g. 'amuse-sse') fails to install properly on an Ubuntu Linux system, while it works fine on macOS.
It raises 'ImportError: amuse is not configured properly' before failing.

**To Reproduce**
- Create a clean virtual environment
- do 'pip install amuse-framework'
- do 'pip install amuse-sse'

**Expected behavior**
It should install.

**Comment by ipelupessy** [comment]
what is the output of "pip install -v .."?

**Comment by rieder** [comment]
```
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Created temporary directory: /tmp/pip-ephem-wheel-cache-bwwbVh
Created temporary directory: /tmp/pip-req-tracker-p0BSAP
Created requirements tracker '/tmp/pip-req-tracker-p0BSAP'
Created temporary directory: /tmp/pip-install-RS2iC5
Collecting amuse-sse
  1 location(s) to search for versions of amuse-sse:
  * https://pypi.org/simple/amuse-sse/
  Getting page https://pypi.org/simple/amuse-sse/
  Looking up "https://pypi.org/simple/amuse-sse/" in the cache
  Request header has "max_age" as 0, cache bypassed
  Starting new HTTPS connection (1): pypi.org:443
  https://pypi.org:443 "GET /simple/amuse-sse/ HTTP/1.1" 304 0
  Analyzing links from page https://pypi.org/simple/amuse-sse/
    Found link https://files.pythonhosted.org/packages/01/e6/beb1aa25f2471e26c349d3a60e7062cf1e00639ed8f166e2b7d3d02524f1/amuse-sse-12.0.0rc1.tar.gz#sha256=90996fef233f30ebd11457ff6651a97770b015646510d726a3325721a6d1ddcb (from https://pypi.org/simple/amuse-sse/), version: 12.0.0rc1
  Using version 12.0.0rc1 (newest of versions: 12.0.0rc1)
  Created temporary directory: /tmp/pip-unpack-qYPgxX
  Looking up "https://files.pythonhosted.org/packages/01/e6/beb1aa25f2471e26c349d3a60e7062cf1e00639ed8f166e2b7d3d02524f1/amuse-sse-12.0.0rc1.tar.gz" in the cache
  Current age based on date: 660209
  Ignoring unknown cache-control directive: immutable
  Freshness lifetime from max-age: 365000000
  The response is "fresh", returning cached response
  365000000 > 660209
  Using cached https://files.pythonhosted.org/packages/01/e6/beb1aa25f2471e26c349d3a60e7062cf1e00639ed8f166e2b7d3d02524f1/amuse-sse-12.0.0rc1.tar.gz
  Downloading from URL https://files.pythonhosted.org/packages/01/e6/beb1aa25f2471e26c349d3a60e7062cf1e00639ed8f166e2b7d3d02524f1/amuse-sse-12.0.0rc1.tar.gz#sha256=90996fef233f30ebd11457ff6651a97770b015646510d726a3325721a6d1ddcb (from https://pypi.org/simple/amuse-sse/)
  Added amuse-sse from https://files.pythonhosted.org/packages/01/e6/beb1aa25f2471e26c349d3a60e7062cf1e00639ed8f166e2b7d3d02524f1/amuse-sse-12.0.0rc1.tar.gz#sha256=90996fef233f30ebd11457ff6651a97770b015646510d726a3325721a6d1ddcb to build tracker '/tmp/pip-req-tracker-p0BSAP'
    Running setup.py (path:/tmp/pip-install-RS2iC5/amuse-sse/setup.py) egg_info for package amuse-sse
    Running command python setup.py egg_info
    running egg_info
    creating pip-egg-info/amuse_sse.egg-info
    writing requirements to pip-egg-info/amuse_sse.egg-info/requires.txt
    writing pip-egg-info/amuse_sse.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/amuse_sse.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/amuse_sse.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/amuse_sse.egg-info/SOURCES.txt'
    reading manifest file 'pip-egg-info/amuse_sse.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '*.pyc' found under directory 'src'
    warning: no previously-included files matching '*.o' found under directory 'src'
    warning: no previously-included files matching '*~' found under directory 'src'
    warning: no previously-included files matching '.pc' found under directory 'src'
    warning: no previously-included files matching 'ccache' found under directory 'src'
    warning: no previously-included files matching '*.a' found under directory 'src'
    writing manifest file 'pip-egg-info/amuse_sse.egg-info/SOURCES.txt'
  Source in /tmp/pip-install-RS2iC5/amuse-sse has version 12.0.0rc1, which satisfies requirement amuse-sse from https://files.pythonhosted.org/packages/01/e6/beb1aa25f2471e26c349d3a60e7062cf1e00639ed8f166e2b7d3d02524f1/amuse-sse-12.0.0rc1.tar.gz#sha256=90996fef233f30ebd11457ff6651a97770b015646510d726a3325721a6d1ddcb
  Removed amuse-sse from https://files.pythonhosted.org/packages/01/e6/beb1aa25f2471e26c349d3a60e7062cf1e00639ed8f166e2b7d3d02524f1/amuse-sse-12.0.0rc1.tar.gz#sha256=90996fef233f30ebd11457ff6651a97770b015646510d726a3325721a6d1ddcb from build tracker '/tmp/pip-req-tracker-p0BSAP'
Requirement already satisfied: wheel>=0.32 in /home/sr621/Env/Amuse2pip/lib/python2.7/site-packages (from amuse-sse) (0.33.1)
Requirement already satisfied: docutils>=0.6 in /home/sr621/Env/Amuse2pip/lib/python2.7/site-packages (from amuse-sse) (0.14)
Requirement already satisfied: numpy>=1.2.2 in /home/sr621/Env/Amuse2pip/lib/python2.7/site-packages (from amuse-sse) (1.16.3)
Requirement already satisfied: nose>=0.11.1 in /home/sr621/Env/Amuse2pip/lib/python2.7/site-packages (from amuse-sse) (1.3.7)
Requirement already satisfied: mpi4py>=1.1.0 in /home/sr621/Env/Amuse2pip/lib/python2.7/site-packages (from amuse-sse) (3.0.1)
Requirement already satisfied: h5py>=1.1.0 in /home/sr621/Env/Amuse2pip/lib/python2.7/site-packages (from amuse-sse) (2.9.0)
Requirement already satisfied: amuse-framework>=12.0.0rc1 in /home/sr621/Env/Amuse2pip/lib/python2.7/site-packages (from amuse-sse) (12.0.0rc2)
Requirement already satisfied: six in /home/sr621/Env/Amuse2pip/lib/python2.7/site-packages (from h5py>=1.1.0->amuse-sse) (1.12.0)
Building wheels for collected packages: amuse-sse
  Created temporary directory: /tmp/pip-wheel-oHBUuo
  Building wheel for amuse-sse (setup.py) ...   Destination directory: /tmp/pip-wheel-oHBUuo
  Running command /home/sr621/Env/Amuse2pip/bin/python2 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-RS2iC5/amuse-sse/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-oHBUuo --python-tag cp27
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/amuse
  creating build/lib.linux-x86_64-2.7/amuse/community
  creating build/lib.linux-x86_64-2.7/amuse/community/sse
  copying src/amuse/community/sse/interface.py -> build/lib.linux-x86_64-2.7/amuse/community/sse
  copying src/amuse/community/sse/__init__.py -> build/lib.linux-x86_64-2.7/amuse/community/sse
  running build_codes
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-RS2iC5/amuse-sse/setup.py", line 75, in <module>
      data_files=all_data_files,
    File "/home/sr621/Env/Amuse2pip/local/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/home/sr621/Env/Amuse2pip/local/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
      self.run_command(cmd_name)
    File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python2.7/distutils/dist.py", line 971, in run_command
      cmd_obj.ensure_finalized()
    File "/usr/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
      self.finalize_options()
    File "support/setup_codes.py", line 798, in finalize_options
      CodeCommand.finalize_options(self)
    File "support/setup_codes.py", line 262, in finalize_options
      from amuse import config
    File "/home/sr621/Env/Amuse2pip/local/lib/python2.7/site-packages/amuse/__init__.py", line 41, in <module>
      raise ImportError("amuse is not configured correctly")
  ImportError: amuse is not configured correctly
error
  ERROR: Failed building wheel for amuse-sse
  Running setup.py clean for amuse-sse
  Running command /home/sr621/Env/Amuse2pip/bin/python2 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-RS2iC5/amuse-sse/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
  running clean
  running clean_codes
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-RS2iC5/amuse-sse/setup.py", line 75, in <module>
      data_files=all_data_files,
    File "/home/sr621/Env/Amuse2pip/local/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "support/setup_codes.py", line 1155, in run
      self.run_command(cmd_name)
    File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python2.7/distutils/dist.py", line 971, in run_command
      cmd_obj.ensure_finalized()
    File "/usr/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
      self.finalize_options()
    File "support/setup_codes.py", line 262, in finalize_options
      from amuse import config
    File "/home/sr621/Env/Amuse2pip/local/lib/python2.7/site-packages/amuse/__init__.py", line 41, in <module>
      raise ImportError("amuse is not configured correctly")
  ImportError: amuse is not configured correctly
  ERROR: Failed cleaning build dir for amuse-sse
Failed to build amuse-sse
Installing collected packages: amuse-sse
  Created temporary directory: /tmp/pip-record-__0X6L
    Running command /home/sr621/Env/Amuse2pip/bin/python2 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-RS2iC5/amuse-sse/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-__0X6L/install-record.txt --single-version-externally-managed --compile --install-headers /home/sr621/Env/Amuse2pip/include/site/python2.7/amuse-sse
  Running setup.py install for amuse-sse ...     usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help

    error: option --single-version-externally-managed not recognized
error
Cleaning up...
  Removing source in /tmp/pip-install-RS2iC5/amuse-sse
Removed build tracker '/tmp/pip-req-tracker-p0BSAP'
ERROR: Command "/home/sr621/Env/Amuse2pip/bin/python2 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-RS2iC5/amuse-sse/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-__0X6L/install-record.txt --single-version-externally-managed --compile --install-headers /home/sr621/Env/Amuse2pip/include/site/python2.7/amuse-sse" failed with error code 1 in /tmp/pip-install-RS2iC5/amuse-sse/
Exception information:
Traceback (most recent call last):
  File "/home/sr621/Env/Amuse2pip/local/lib/python2.7/site-packages/pip/_internal/cli/base_command.py", line 178, in main
    status = self.run(options, args)
  File "/home/sr621/Env/Amuse2pip/local/lib/python2.7/site-packages/pip/_internal/commands/install.py", line 414, in run
    use_user_site=options.use_user_site,
  File "/home/sr621/Env/Amuse2pip/local/lib/python2.7/site-packages/pip/_internal/req/__init__.py", line 58, in install_given_reqs
    **kwargs
  File "/home/sr621/Env/Amuse2pip/local/lib/python2.7/site-packages/pip/_internal/req/req_install.py", line 953, in install
    spinner=spinner,
  File "/home/sr621/Env/Amuse2pip/local/lib/python2.7/site-packages/pip/_internal/utils/misc.py", line 776, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command "/home/sr621/Env/Amuse2pip/bin/python2 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-RS2iC5/amuse-sse/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-__0X6L/install-record.txt --single-version-externally-managed --compile --install-headers /home/sr621/Env/Amuse2pip/include/site/python2.7/amuse-sse" failed with error code 1 in /tmp/pip-install-RS2iC5/amuse-sse/
```

**Comment by ipelupessy** [comment]
its working here (opensuse tumbleweed)

have you cleared/ disabled the pip cache? (there were amuse versions where the config thing was broken) 
 
can you check whether the amuse dir ( /home/sr621/Env/Amuse2pip/local/lib/python2.7/site-packages/amuse/) contains config.py and config.mk (and that their contents make sense)?

**Comment by rieder** [comment]
This is on a clean virtualenv, on a machine where I did not try this before...
Also, people in Leiden had similar (or the same) problems on their tries.
Both config files exist and make sense.

**Comment by ipelupessy** [comment]
can you try:
```
from amuse import config
```
on the python command line?

**Comment by rieder** [comment]
trying `from amuse import config` manually gives this:
```
>>> from amuse import config
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sr621/Env/Amuse2pip/local/lib/python2.7/site-packages/amuse/__init__.py", line 28, in <module>
    import numpy
  File "/home/sr621/Env/Amuse2pip/local/lib/python2.7/site-packages/numpy/__init__.py", line 145, in <module>
    from . import lib
  File "/home/sr621/Env/Amuse2pip/local/lib/python2.7/site-packages/numpy/lib/__init__.py", line 24, in <module>
    from .npyio import *
  File "/home/sr621/Env/Amuse2pip/local/lib/python2.7/site-packages/numpy/lib/npyio.py", line 13, in <module>
    from . import format
  File "/home/sr621/Env/Amuse2pip/local/lib/python2.7/site-packages/numpy/lib/format.py", line 161, in <module>
    import io
  File "io/__init__.py", line 8, in <module>
    from amuse.io.base import *
  File "/home/sr621/Env/Amuse2pip/local/lib/python2.7/site-packages/amuse/io/__init__.py", line 8, in <module>
    from amuse.io.base import *
  File "/home/sr621/Env/Amuse2pip/local/lib/python2.7/site-packages/amuse/io/base.py", line 6, in <module>
    from amuse.support.core import late
  File "/home/sr621/Env/Amuse2pip/local/lib/python2.7/site-packages/amuse/support/__init__.py", line 3, in <module>
    from amuse.support.options import option
  File "/home/sr621/Env/Amuse2pip/local/lib/python2.7/site-packages/amuse/support/options.py", line 11, in <module>
    import pkg_resources
  File "/home/sr621/Env/Amuse2pip/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 26, in <module>
    import zipfile
  File "/usr/lib/python2.7/zipfile.py", line 501, in <module>
    class ZipExtFile(io.BufferedIOBase):
AttributeError: 'module' object has no attribute 'BufferedIOBase'
```

**Comment by ipelupessy** [comment]
this seems an import error in the zipfile similar to 
https://stackoverflow.com/questions/32657580/class-gzipfileio-bufferediobase-attributeerror-module-object-has-no-attrib

**Comment by ipelupessy** [comment]
also it seems numpy starts import amuse.io? I wonder why the imports work differently...what is the python version?

**Comment by rieder** [comment]
Python 2.7.15rc1

When I unpack the zipfile and manually try installing (python setup.py install), it fails in the same way...

**Comment by rieder** [comment]
```
>>> import zipfile
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/zipfile.py", line 6, in <module>
    import io
  File "io/__init__.py", line 8, in <module>
    from amuse.io.base import *
  File "/home/sr621/Env/Amuse2pip/local/lib/python2.7/site-packages/amuse/__init__.py", line 28, in <module>
    import numpy
  File "/home/sr621/Env/Amuse2pip/local/lib/python2.7/site-packages/numpy/__init__.py", line 140, in <module>
    from . import _distributor_init
ImportError: cannot import name _distributor_init
```

This seems wrong.

**Comment by rieder** [comment]
Please ignore the last entries (I'll delete them) - I was in a wrong directory for doing this. Original problem persists though.

**Comment by rieder** [comment]
Trying `from amuse import config` gives this:
```
>>> from amuse import config
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sr621/Env/Amuse2pip/local/lib/python2.7/site-packages/amuse/__init__.py", line 41, in <module>
    raise ImportError("amuse is not configured correctly")
ImportError: amuse is not configured correctly
```

**Comment by ipelupessy** [comment]
can you try:
from amuse.support import get_amuse_root_dir
and print get_amuse_root_dir()
?

**Comment by rieder** [comment]
Commenting out the last lines in __init__.py in the site-packages/amuse/ gives this on retrying 'from amuse import config' (same output for the question above):
```
>>> from amuse import config
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sr621/Env/Amuse2pip/local/lib/python2.7/site-packages/amuse/config.py", line 25, in <module>
    configmk=parse_configmk(os.path.join(get_amuse_root_dir(),"config.mk"))
  File "/home/sr621/Env/Amuse2pip/local/lib/python2.7/site-packages/amuse/support/__init__.py", line 35, in get_amuse_root_dir
    return _Defaults().amuse_root_dir
  File "/home/sr621/Env/Amuse2pip/local/lib/python2.7/site-packages/amuse/support/options.py", line 175, in __get__
    value = self.global_options.get_value_for_option(self, instance)
  File "/home/sr621/Env/Amuse2pip/local/lib/python2.7/site-packages/amuse/support/options.py", line 97, in get_value_for_option
    return option.get_defaultvalue(instance)
  File "/home/sr621/Env/Amuse2pip/local/lib/python2.7/site-packages/amuse/support/options.py", line 186, in get_defaultvalue
    return self.specification_method(instance)
  File "/home/sr621/Env/Amuse2pip/local/lib/python2.7/site-packages/amuse/support/__init__.py", line 32, in amuse_root_dir
    raise exceptions.AmuseException("Could not locate AMUSE root directory! set the AMUSE_DIR variable")
amuse.support.exceptions.AmuseException: Could not locate AMUSE root directory! set the AMUSE_DIR variable
```

**Comment by rieder** [comment]
on macOS this works fine (output is ```/Users/rieder/Env/Amuse2pip/share/amuse```)

**Comment by ipelupessy** [comment]
aha..could you try to find out where the share dir is?

**Comment by rieder** [comment]
Should be ```/home/sr621/Env/Amuse2pip/share/amuse```...

**Comment by ipelupessy** [comment]
if it is, that would explain the error (code is checking some relative paths, in this case it will expect it to be in /home/sr621/Env/Amuse2pip/local/share

I can add this case, or is there some environment variable that indicates the location of the share??

**Comment by rieder** [comment]
No, this is default (for any virtualenv).

**Comment by ipelupessy** [comment]
No, it is not for my virtualenv...will add this case though...also i am trying to look where pip gets it dirs from...

**Comment by ipelupessy** [comment]
done

**Comment by rieder** [comment]
Hmm, I certainly didn't set anything manually...

**Comment by ipelupessy** [comment]
pip's ways are mysterious...
(how do you generate your virtualenvs?)

**Comment by rieder** [comment]
For python2: with 'virtualenv $(virtualenv-name)'.
This is the same for Ubuntu and macOS - and they generate the same directory structure. So why this works on macOS but not Ubuntu...???

**Comment by rieder** [comment]
But I can confirm the problem is now solved.

**Comment by rieder** [comment]
(uploaded amuse-framework 12.0.0rc3 to include this fix)

**Comment by ipelupessy** [comment]
ok, great! it would be nice to find out how to get the data/ config directories in install of setup.py...
