### ISSUE TITLE
OpenMPI Issues Causing "AttributeError: 'function' object has no attribute 'threaded'"

### ISSUE THREAD

**Issue by JPGlaser** [amusecode/amuse#51]
Hello Everyone,

I have been having some issues running AMUSE example codes after compiling from source. Specifically the error that returns on my desktop (AMD Phenom II 6-Core, 8 GB RAM, fresh install of Fedora 23) and our local RedHat cluster is:
````
[jglaser@localhost amuse]$ mpiexec -np 1 python examples/simple/cluster.py
Traceback (most recent call last):
  File "examples/simple/cluster.py", line 132, in <module>
    9.0 | nbody_system.time
  File "examples/simple/cluster.py", line 35, in simulate_small_cluster
    gravity = Hermite(number_of_workers = number_of_workers)
  File "/home/jglaser/amuse/src/amuse/community/hermite0/interface.py", line 208, in __init__
    legacy_interface = HermiteInterface(**options)
  File "/home/jglaser/amuse/src/amuse/community/hermite0/interface.py", line 25, in __init__
    **options)
  File "/home/jglaser/amuse/src/amuse/rfi/core.py", line 581, in __init__
    self._start(name_of_the_worker = name_of_the_worker, **options)
  File "/home/jglaser/amuse/src/amuse/rfi/core.py", line 591, in _start
    self.channel = self.channel_factory(name_of_the_worker, type(self), interpreter_executable = interpreter_executable, **options)
  File "/home/jglaser/amuse/src/amuse/rfi/channel.py", line 1108, in __init__
    self.ensure_mpi_initialized()
  File "/home/jglaser/amuse/src/amuse/rfi/channel.py", line 1140, in ensure_mpi_initialized
    if rc.threaded:
AttributeError: 'function' object has no attribute 'threaded'
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[50049,1],0]
  Exit code:    1
--------------------------------------------------------------------------

````

I am compiling with the correct OpenMPI directory (/usr/lib64/openmpi) and reinstalling mpi4py returns the following linking scheme:
````
[jglaser@localhost amuse]$ ldd /home/jglaser/anaconda2/lib/python2.7/site-packages/mpi4py/MPI.so
	linux-vdso.so.1 (0x00007ffeeff40000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f123b0b8000)
	libpython2.7.so.1.0 => /home/jglaser/anaconda2/lib/libpython2.7.so.1.0 (0x00007f123acd0000)
	libmpi.so.1 => /usr/lib64/openmpi/lib/libmpi.so.1 (0x00007f123a9ed000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f123a7d0000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f123a40e000)
	/lib64/ld-linux-x86-64.so.2 (0x000055fe46260000)
	libutil.so.1 => /lib64/libutil.so.1 (0x00007f123a20b000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f1239f09000)
	libopen-rte.so.7 => /usr/lib64/openmpi/lib/libopen-rte.so.7 (0x00007f1239c8c000)
	libopen-pal.so.6 => /usr/lib64/openmpi/lib/libopen-pal.so.6 (0x00007f1239a02000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f12397fa000)
	libhwloc.so.5 => /lib64/libhwloc.so.5 (0x00007f12395c0000)
	libevent-2.0.so.5 => /lib64/libevent-2.0.so.5 (0x00007f1239377000)
	libevent_pthreads-2.0.so.5 => /lib64/libevent_pthreads-2.0.so.5 (0x00007f1239174000)
	libnuma.so.1 => /lib64/libnuma.so.1 (0x00007f1238f68000)
	libltdl.so.7 => /lib64/libltdl.so.7 (0x00007f1238d5e000)
````

Which seems to be just fine. So my question to you all is: have any of you seen this error before? And if so, is there a common way to work around it?

~ Joe Glaser

**Comment by JPGlaser** [comment]
Alright, fixed the issue with the help of one of our undergrad students who found the issue recently. Thanks Andrew!

It appears to be that when mpi4py went to version 2, threaded was changed to threads with no reverse comparability. Changing line 1140 in amuse/rfi/channel.py in AMUSE version 10.0's source to reflect the change fixes this issue. 

~ Joe Glaser
