### ISSUE TITLE
error using particlesets read in from version 2 format

### ISSUE THREAD

**Issue by ipelupessy** [amusecode/amuse#56]
the following script:

```
from amuse.io import write_set_to_file,read_set_from_file
from amuse.ic.plummer import new_plummer_model
p=new_plummer_model(100)
write_set_to_file(p,"test","amuse",append_to_file=False, version="2.0")
p=read_set_from_file("test","amuse")
p.new_attribute=2*p.mass
```

generates an error:

```
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    p.new_attribute=2*p.mass
  File "/home/inti/code/amuse/amuse/src/amuse/datamodel/particles.py", line 1106, in __setattr__
    self.set_values_in_store(None, [name_of_the_attribute], [self._convert_from_entities_or_quantities(value)])
  File "/home/inti/code/amuse/amuse/src/amuse/datamodel/particles.py", line 1358, in set_values_in_store
    self._private.attribute_storage.set_values_in_store(indices, attributes, values)
  File "/home/inti/code/amuse/amuse/src/amuse/io/store_v2.py", line 483, in set_values_in_store
    self.attributesgroup
  File "/home/inti/code/amuse/amuse/src/amuse/io/store_v2.py", line 70, in new_attribute
    dataset = group.create_dataset(name, shape=shape, dtype=input.number.dtype)
  File "/home/inti/code/amuse/prerequisites/lib/python2.7/site-packages/h5py/_hl/group.py", line 69, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "/home/inti/code/amuse/prerequisites/lib/python2.7/site-packages/h5py/_hl/dataset.py", line 49, in make_new_dset
    shape = tuple(shape)
TypeError: 'int' object is not iterable
Exit 1
```

it does not if the version=2.0 is omitted

**Comment by arjenve** [comment]
I've updated the code so that it will work, but you'll need an extra parameter 'allow_writing' to be set to True.

The real cause is in a non-backward compatible change in version 2, for version 1 we always make a "working copy" (an in memory version of the set), for version 2 this depends on an option (by default no working copy).

This is the option:

return_working_copy
    If set to True, return a working copy in memory you can manipulate,
    savepoint etc. Only available for version 2.0 in version 1.0
    a working copy (i.e. a particles set or grid in memory)
    is always returned. (default: False)

So another fix is to do:

read_set_from_file("test","amuse", return_working_copy=True)

**Comment by ipelupessy** [comment]
so what does allow_writing do? (will this change the file?)

**Comment by ipelupessy** [comment]
and maybe return_working_copy=True would be what naieve users would expect?

**Comment by ipelupessy** [comment]
closing, but there will be a new one for this
