### ISSUE TITLE
question about one sample application script

### ISSUE THREAD

**Issue by ykzivio** [amusecode/amuse#568]
`amuse/examples/applications/test_riemann_shock_tube_problem.py` 
This is the script I have some issue with, this script runs perfectly when I run it with grid-based hydro code with the command ` python test_riemann_shock_tube_problem.py -n 40 -c athena`
but when I try to run it with sph code with the following command `python test_riemann_shock_tube_problem.py -c gadget2 -p 1000` some wired thing that I cannot solve happens. I was wondering if someone could give me some suggestions?
```
calculating shock using exact solution
calculating shock using code
number_of_workers 2
name_of_the_code gadget2
number_of_grid_points 10
number_of_particles 1000
[gonzales:24072] [[3575,1],0] FORKING HNP: orted --hnp --set-sid --report-uri 15 --singleton-died-pipe 16 -mca state_novm_select 1 -mca ess_base_jobid 234291200
Grid.create deprecated, use new_regular_grid instead
Traceback (most recent call last):
  File "test_riemann_shock_tube_problem.py", line 506, in <module>
    main(**options.__dict__)
  File "test_riemann_shock_tube_problem.py", line 469, in main
    grids = model.get_solution_at_time(0.12 | time)
  File "test_riemann_shock_tube_problem.py", line 373, in get_solution_at_time
    self.set_initial_conditions(instance)
  File "test_riemann_shock_tube_problem.py", line 336, in set_initial_conditions
    initial_grid, self.number_of_particles)
  File "/home/kuangy/amuse_new/amuse/src/amuse/ext/grid_to_sph.py", line 114, in convert_grid_to_SPH
    return converter.result
  File "/home/kuangy/amuse_new/amuse/src/amuse/ext/grid_to_sph.py", line 81, in result
    self.setup_lookup_tables()
  File "/home/kuangy/amuse_new/amuse/src/amuse/ext/grid_to_sph.py", line 43, in setup_lookup_tables
    self.velocity_lookup_table = (self.grid.momentum / density.reshape(shape_for_vector_multiply)).reshape((-1,3))
  File "/home/kuangy/amuse_new/amuse/src/amuse/datamodel/base.py", line 774, in __getattr__
    " but this attribute is not defined for this set.".format(name_of_the_attribute))
AttributeError: You tried to access attribute 'momentum' but this attribute is not defined for this set.
```

**Comment by ipelupessy** [comment]
this looks like a bug in the script...

**Comment by ykzivio** [comment]
> this looks like a bug in the script...

I have not made any change to the original script. I looked into the base.py script and did not find anything related to the attribute `momentum`. Don't understand the reason causes this.

**Comment by ipelupessy** [comment]
I have found the problem..I will push a fix..

**Comment by ipelupessy** [comment]
so I have commited a fix..note that for this problem an SPH code will need considerably more points than 1000 for remotely good results though..

**Comment by ipelupessy** [comment]
if you want, you can fix it in the script:by adding a line:
```
    def set_initial_conditions(self, instance):
        if self.name_of_the_code in self.sph_hydro_codes:
            initial_grid = self.new_grid()
            initial_grid.add_global_vector_attribute("momentum", ["rhovx","rhovy","rhovz"]) #<-added
            self.initialize_grid_with_shock(initial_grid)

```

**Comment by ipelupessy** [comment]
(so you do not need to reinstall or wait for a release)

**Comment by ipelupessy** [comment]
fixed
