### ISSUE TITLE
Issue while executing the command : pip install --no-use-pep517 amuse-framework

### ISSUE THREAD

**Issue by Sudina** [amusecode/amuse#578]
Environment :
Windows 10
Python 3.7.4
pip 20.0.2
```    
cwd: C:\Users\Aiswarya\AppData\Local\Temp\pip-install-sotvniqp\amuse-framework\
  Complete output (60 lines):
  running bdist_wheel
  running build
  running configure_codes
  get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'
  customize GnuFCompiler
  Could not locate executable g77
  Could not locate executable f77
  customize IntelVisualFCompiler
  Could not locate executable ifort
  Could not locate executable ifl
  customize AbsoftFCompiler
  Could not locate executable f90
  customize CompaqVisualFCompiler
  Could not locate executable DF
  customize IntelItaniumVisualFCompiler
  Could not locate executable efl
  customize Gnu95FCompiler
  Could not locate executable gfortran
  Could not locate executable f95
  customize G95FCompiler
  Could not locate executable g95
  customize IntelEM64VisualFCompiler
  customize IntelEM64TFCompiler
  Could not locate executable efort
  Could not locate executable efc
  customize PGroupFlangCompiler
  Could not locate executable flang
  don't know how to compile Fortran code on platform 'nt'
  Running configure for AMUSE
  config.mk not generated; output of configure:
  '.' is not recognized as an internal or external command,
  operable program or batch file.

  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\Aiswarya\AppData\Local\Temp\pip-install-sotvniqp\amuse-framework\setup.py", line 78, in <module>
      scripts=[ "bin/amusifier" ],
    File "c:\users\aiswarya\amuse-env\lib\site-packages\setuptools\__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\Aiswarya\AppData\Local\Programs\Python\Python37\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Users\Aiswarya\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "C:\Users\Aiswarya\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "c:\users\aiswarya\amuse-env\lib\site-packages\wheel\bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "C:\Users\Aiswarya\AppData\Local\Programs\Python\Python37\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\Aiswarya\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\Aiswarya\AppData\Local\Programs\Python\Python37\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\Users\Aiswarya\AppData\Local\Programs\Python\Python37\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\Aiswarya\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\Aiswarya\AppData\Local\Temp\pip-install-sotvniqp\amuse-framework\support\setup_codes.py", line 1153, in run
      raise Exception("configure failed")
  Exception: configure failed
  ----------------------------------------
  ERROR: Failed building wheel for amuse-framework
  Running setup.py clean for amuse-framework
Failed to build amuse-framework
Installing collected packages: amuse-framework
    Running setup.py install for amuse-framework ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\aiswarya\amuse-env\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Aiswarya\\AppData\\Local\\Temp\\pip-install-sotvniqp\\amuse-framework\\setup.py'"'"'; __file__='"'"'C:\\Users\\Aiswarya\\AppData\\Local\\Temp\\pip-install-sotvniqp\\amuse-framework\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Aiswarya\AppData\Local\Temp\pip-record-bm3qj5he\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\aiswarya\amuse-env\include\site\python3.7\amuse-framework'
         cwd: C:\Users\Aiswarya\AppData\Local\Temp\pip-install-sotvniqp\amuse-framework\
    Complete output (6 lines):
    usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: setup.py --help [cmd1 cmd2 ...]
       or: setup.py --help-commands
       or: setup.py cmd --help

    error: option --single-version-externally-managed not recognized
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\aiswarya\amuse-env\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Aiswarya\\AppData\\Local\\Temp\\pip-install-sotvniqp\\amuse-framework\\setup.py'"'"'; __file__='"'"'C:\\Users\\Aiswarya\\AppData\\Local\\Temp\\pip-install-sotvniqp\\amuse-framework\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Aiswarya\AppData\Local\Temp\pip-record-bm3qj5he\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\aiswarya\amuse-env\include\site\python3.7\amuse-framework' Check the logs for full command output.
```

**Comment by rieder** [comment]
AMUSE is not natively supported on Windows I'm afraid.
It will work under the Windows subsystem for Linux though (see https://docs.microsoft.com/en-us/windows/wsl/install-win10).

**Comment by rieder** [comment]
I'm closing this issue, but please do let us know if you have any further issues installing AMUSE in the subsystem!
