### ISSUE TITLE
amuse.units.core.IncompatibleUnitsException

### ISSUE THREAD

**Issue by arpanastrocanada** [amusecode/amuse#606]
Hello all, 

I am getting this for a script I am running using Amuse. However when I use the same code for just a different physics it ran without any problem. I couldn't figure out what is happening.

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/amuse/support/core.py", line 518, in memof
    return memof.d[arg]
KeyError: (unit<none>, unit<3.839e+26 * s**-1>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "2_infinite_radial_constant.py", line 1065, in <module>
    stars = handle_encounter(stars, index1, index2, mr_mode)
  File "2_infinite_radial_constant.py", line 540, in handle_encounter
    p.mass  = (stars[index1].mass+stars[index2].mass)*(1-0.157*(q/(1+q)**2)*(826.92*M2/tkh2+241.11*M1**(0.5))/(480.76*M2/tkh2+183.84*M1**(0.5)))
  File "/usr/local/lib/python3.7/site-packages/amuse/units/quantities.py", line 108, in __add__
    factor = other.unit.conversion_factor_from(self.unit)
  File "/usr/local/lib/python3.7/site-packages/amuse/support/core.py", line 520, in memof
    result=f(*arg)
  File "/usr/local/lib/python3.7/site-packages/amuse/units/core.py", line 302, in conversion_factor_from
    raise IncompatibleUnitsException(x, self)
amuse.units.core.IncompatibleUnitsException: Cannot express none in 3.839e+26 * s**-1, the units do not have the same bases

**Comment by ipelupessy** [comment]
it looks like an error in the mentioned line 540 in 2_infinite_radial_constant.py - but i am not sure.. can you post the lines around this and maybe a printout of all the variable used in this line (its a bit hard to read the line because of the formatting..)

**Comment by ipelupessy** [comment]
this looked like a syntax error in user script; please follow up if necessary by reponening, closing for now.
