### ISSUE TITLE
GPU Issues with PIP-Installed PH4

### ISSUE THREAD

**Issue by JPGlaser** [amusecode/amuse#615]
**Describe the bug**
It seems that currently, PH4 when installed via PIP does not build the ph4_gpu_worker.

**To Reproduce**
Run any PH4-related script with gpu workers turned on.

**Expected behavior**
Start the job with a number of gpu workers allocated to the number of specified GPUs (one per unit, ideally).

**Logs**
```
Traceback (most recent call last):
  File "/home/draco/jglaser/GitHub/Tycho/sim_cluster.py", line 372, in <module>
    convert_nbody = LargeScaleConverter)
  File "/home/draco/amuse/anaconda3/lib/python3.7/site-packages/amuse/community/ph4/interface.py", line 471, in __init__
    legacy_interface = ph4Interface(**keyword_arguments)
  File "/home/draco/amuse/anaconda3/lib/python3.7/site-packages/amuse/community/ph4/interface.py", line 34, in __init__
    **options
  File "/home/draco/amuse/anaconda3/lib/python3.7/site-packages/amuse/rfi/core.py", line 752, in __init__
    self._start(name_of_the_worker = name_of_the_worker, **options)
  File "/home/draco/amuse/anaconda3/lib/python3.7/site-packages/amuse/rfi/core.py", line 771, in _start
    self.channel = self.channel_factory(name_of_the_worker, type(self), interpreter_executable = interpreter_executable, **options)
  File "/home/draco/amuse/anaconda3/lib/python3.7/site-packages/amuse/rfi/channel.py", line 898, in __init__
    self.full_name_of_the_worker = self.get_full_name_of_the_worker(legacy_interface_type)
  File "/home/draco/amuse/anaconda3/lib/python3.7/site-packages/amuse/rfi/channel.py", line 704, in get_full_name_of_the_worker
    raise exceptions.CodeException("The worker application does not exist, it should be at: \n{0}".format('\n'.join(tried_workers)))
amuse.support.exceptions.CodeException: The worker application does not exist, it should be at: 
/home/draco/amuse/anaconda3/lib/python3.7/site-packages/amuse/_workers/ph4_worker_gpu
/home/draco/amuse/anaconda3/lib/python3.7/site-packages/amuse/_workers/ph4_worker_gpu
/home/draco/amuse/anaconda3/lib/python3.7/site-packages/amuse/community/ph4/ph4_worker_gpu
/home/draco/amuse/anaconda3/lib/python3.7/site-packages/amuse/rfi/ph4_worker_gpu

```

**Environment (please complete the following information):**
 - Centos & Ubuntu 18 LTS
 - Anaconda 3.7+ with AMUSE installed via PIP

**Comment by blackhole-canada** [comment]
Hi, 

In order to use the GPU version you need to build the codes from source using ./configure --enable-cuda. Pip doesn't install the GPU version. Building from the source is a bit tricky but it works.

**Comment by JPGlaser** [comment]
Yeah, though I find it a bit odd that we dont have a gpu builder on pip (though I admit I am still getting prepping packages for pip distribution).

@rieder Any ideas on prepping methods that might make this a possibility in the future?

**Comment by rieder** [comment]
I think the only thing blocking this is that amuse-framework doesn't automatically detect if CUDA should be enabled (and therefore also won't build the sapporo library). 
Not sure how we could make it detect this automatically (though it shouldn't be too difficult).

The pip version of amuse-ph4 should build a GPU worker if it is enabled.

**Comment by JPGlaser** [comment]
@rieder is there a flag that should be passed to enable building the worker when installing amuse-ph4 from pip?

I have collaborators that would much rather that be the option than messing around with the source compilation.

~ Joe G.

**Comment by JPGlaser** [comment]
@blackhole-canada @stevemcmillan 
So, I have been building AMUSE 13.1 via source to see if I can get PH4-GPU working. However, it is failing to install due to the following error:
```
ranlib libph4gpu.a
make[2]: Leaving directory `/home/draco/jglaser/GitHub/amuse/src/amuse/community/ph4/src'
mpicxx -g -O2 -fPIC -g -O2 -fPIC -Wall -g -O2 -I/home/draco/jglaser/GitHub/amuse/lib/stopcond  worker_code.cc interface.o src/libph4gpu.a -o ph4_worker_gpu  -L/home/draco/j$
worker_code.cc: In function ‘void run_mpi(int, char**)’:
worker_code.cc:1301:74: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int i = 0; i < (sizeof abort_signals) / (sizeof abort_signals[0]); i++) {
                                                                          ^
worker_code.cc: At global scope:
worker_code.cc:29:13: warning: ‘NEEDS_MPI’ defined but not used [-Wunused-variable]
 static bool NEEDS_MPI = true;
             ^
worker_code.cc:60:13: warning: ‘TRUE_BYTE’ defined but not used [-Wunused-variable]
 static bool TRUE_BYTE = 1;
             ^
worker_code.cc:61:13: warning: ‘FALSE_BYTE’ defined but not used [-Wunused-variable]
 static bool FALSE_BYTE = 0;
             ^
/usr/bin/ld: cannot find -lsapporo
collect2: error: ld returned 1 exit status
make[1]: *** [ph4_worker_gpu] Error 1
make[1]: Leaving directory `/home/draco/jglaser/GitHub/amuse/src/amuse/community/ph4'
```
The following are the system variables:
```
AMUSE_DIR	/home/draco/jglaser/GitHub/amuse
BOOSTLIBS	
CC	gcc
CFLAGS	-g -O2 -fPIC
CUDA_LIBDIRS	-L/cm/shared/apps/cuda55/toolkit/5.5.22/lib -L/cm/shared/apps/cuda55/toolkit/5.5.22/lib64
CUDA_LIBS	-L/cm/images/default-image/cm/local/apps/cuda-driver/libs/331.75/lib64 -lcuda  -L/cm/shared/apps/cuda55/toolkit/5.5.22/lib64 -lcudart
CUDA_SDK	/TOBEFIXED
CUDA_TK	/cm/shared/apps/cuda55/toolkit/5.5.22
CXX	g++
CXXFLAGS	-g -O2 -fPIC
F90	gfortran
FC	gfortran
FFLAGS	-g -O2 -fPIC
FFTW_FLAGS	
FFTW_LIBS	-lfftw3 -lm   -lfftw3_threads
FORTRAN	gfortran
GSL_FLAGS	
GSL_LIBS	-lgsl -lgslcblas -lm
JAR	/usr/bin/jar
JAVA	/usr/bin/java
JAVAC	/usr/bin/javac
MPICC	mpicc
MPICXX	mpicxx
MPIF90	mpif90
MUSE_PACKAGE_DIR	/home/draco/jglaser/GitHub/amuse
OPENMP_CFLAGS	-fopenmp
OPENMP_FCFLAGS	-fopenmp
PYTHON	/home/draco/amuse/anaconda3/bin/python
SAPPORO_LIBS	-L/home/draco/jglaser/GitHub/amuse/lib/sapporo-2 -lsapporo -fopenmp
```
Any ideas here, since this will need to be ironed out for the pip install version anyway?

~ Joe G.

**Comment by JPGlaser** [comment]
Update for today:
I have ph4 with its gpu worker for AMUSE 13 compiling correctly against Anaconda 3.7. I had to switch from sapporo_2 to sapporo_light in the Makefile's library call, but for now everything is working (thanks @stevemcmillan for the suggestion).

I'll see what is going on with sapporo_2 in the near future unless anyone has any insights on this.

~ Joe G.
