### ISSUE TITLE
PIP Issues during --User Install Method

### ISSUE THREAD

**Issue by JPGlaser** [amusecode/amuse#690]
**Describe the bug**
When installing amuse community codes via `pip install amuse-CODE --user`, an error is raised due to PEP 517.

**To Reproduce**
As a non-owner of the python directory, run `pip install amuse-kepler --user`.

**Expected behavior**
Successful build of wheel and installation of Kepler/SmallN/etc.

**Logs**
```
  Community codes not built (because of errors):
  ================================================================================
   * kepler
  ================================================================================
  0 out of 1 codes built, 0 out of 0 libraries built
  Traceback (most recent call last):
    File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 205, in build_wheel
      metadata_directory)
    File "/tmp/pip-build-env-ugyvbb5r/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 217, in build_wheel
      wheel_directory, config_settings)
    File "/tmp/pip-build-env-ugyvbb5r/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 202, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/pip-build-env-ugyvbb5r/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 254, in run_setup
      self).run_setup(setup_script=setup_script)
    File "/tmp/pip-build-env-ugyvbb5r/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 145, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 54, in <module>
      data_files=all_data_files,
    File "/tmp/pip-build-env-ugyvbb5r/overlay/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/opt/conda/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/opt/conda/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/opt/conda/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-ugyvbb5r/overlay/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 290, in run
      self.run_command('build')
    File "/opt/conda/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/opt/conda/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/opt/conda/lib/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/opt/conda/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/opt/conda/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-0ply3vli/amuse-kepler/support/setup_codes.py", line 1093, in run
      raise Exception("No succesful builds detected. Aborting.")
  Exception: No succesful builds detected. Aborting.
  ----------------------------------------
  ERROR: Failed building wheel for amuse-kepler
Failed to build amuse-kepler
ERROR: Could not build wheels for amuse-kepler which use PEP 517 and cannot be installed directly
```

**Environment (please complete the following information):**
 - OS and version: Ubuntu 18.04.1 LTS
 - Python Version: Python 3.7.6

**Comment by ipelupessy** [comment]
its a build failure - probably this can be debugged further with the build.log file... ```pip install --user -v --no-clean ..``` and then search for it in /tmp
