### ISSUE TITLE
Problem with Installation of mesa

### ISSUE THREAD

**Issue by ritikshah44** [amusecode/amuse#708]
I tried running merge_two_stars.py from the syllabus folder but I am getting an error that code mesa not available.
```
Traceback (most recent call last):
  File "merge_two_stars.py", line 50, in <module>
    radius, rho = merge_two_stars(**o.__dict__)
  File "merge_two_stars.py", line 13, in merge_two_stars
    stellar = MESA()
  File "/home/ritik_shah/.local/lib/python3.8/site-packages/amuse/lab.py", line 133, in __init__
    raise Exception(
Exception: failed import, code mesa not available, maybe it needs to be (pip) installed?
```
I then installed mesa via "pip3 install mesa" but the issue still remains the same

I also tried using "make mesa.code DOWNLOAD_CODES=1"
But getting another error that:
```
python setup.py -v build_code --inplace --clean=yes --code-name=mesa
running build_code
cleaning src/amuse/community/mesa
make -C src/amuse/community/mesa clean
make[1]: Entering directory '/home/ritik_shah/Desktop/amuse-13.2.0/src/amuse/community/mesa'
Traceback (most recent call last):
  File "setup.py", line 93, in <module>
    python_requires=">=3.5"
  File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/ritik_shah/Desktop/amuse-13.2.0/support/setup_codes.py", line 1214, in run
    BuildCodes.run(self)
  File "/home/ritik_shah/Desktop/amuse-13.2.0/support/setup_codes.py", line 887, in run
    self.do_clean()
  File "/home/ritik_shah/Desktop/amuse-13.2.0/support/setup_codes.py", line 789, in do_clean
    self.call(['make','-C', x, 'clean'], env=environment)
  File "/home/ritik_shah/Desktop/amuse-13.2.0/support/setup_codes.py", line 760, in call
    stringio.write(str(line, 'utf-8'))
TypeError: str() takes at most 1 argument (2 given)
make: *** [Makefile:124: mesa.code] Error 1
```

So how should I proceed ahead?

**Comment by rieder** [comment]
`pip3 install mesa` does not install the AMUSE version of MESA. Currently, the amuse-mesa package is not yet installable via pip (we're working on that). To use AMUSE with MESA, you would currently have to do the 'developer install' of AMUSE, see https://github.com/amusecode/amuse#amuse-development.

**Comment by rieder** [comment]
Also, it appears you are using Python 2.7 in the second problem, this will not work with the current version of AMUSE.

**Comment by ritikshah44** [comment]
I am always using python 3.8 version for amuse but I cannot figure why does it use 2.7 version. How to change this?

**Comment by rieder** [comment]
This should be set by running ./configure in the AMUSE dir, if you are running in a virtual environment (as described on the website).
