### ISSUE TITLE
Facing issue with running hydro_simple, stellar_simple.py

### ISSUE THREAD

**Issue by ritikshah44** [amusecode/amuse#709]
When I am running the code for hydri_simple.py or even stellar_simple.py, I am facing same issue of opening file is false
python3 hydro_simple.py
Invalid MIT-MAGIC-COOKIE-1 keyTraceback (most recent call last):
  File "hydro_simple.py", line 55, in <module>
    main(**o.__dict__)
  File "hydro_simple.py", line 17, in main
    write_set_to_file(bodies.savepoint(0.0 | t_end.unit), "hydro.hdf5", "hdf5",append_to_file=False)
  File "/home/ritik_shah/.local/lib/python3.8/site-packages/amuse/io/base.py", line 72, in write_set_to_file
    processor.store()
  File "/home/ritik_shah/.local/lib/python3.8/site-packages/amuse/io/store.py", line 96, in store
    processor = store_v2.StoreHDF(
  File "/home/ritik_shah/.local/lib/python3.8/site-packages/amuse/io/store_v2.py", line 642, in __init__
    raise Exception("Opening file for write with overwrite_file is False but file {0} exists".format(filename))
Exception: Opening file for write with overwrite_file is False but file hydro.hdf5 exists

Cannot figure out how to resolve this issue, can you help?

**Comment by rieder** [comment]
either set `overwrite_file=True` in write_set_to_file, or delete the hydro.hdf5 file manually.
