### ISSUE TITLE
Issue with PeTar when bridging with Fi and Nsph >~ 16000

### ISSUE THREAD

**Issue by PaoloSuin** [amusecode/amuse#714]
Hey all,
I am trying to run a simulation of the evolution of SPH cloud interacting with a stellar cluster, coupling Fi and PeTar with Bridge
Apparently an error appears in PeTar when trying to describe the gas with more than ~16000 particles (2^14).
The error comes out at the moment of interaction, independently of the distance between the cloud and the cluster (initially set to 10^2 * Rcloud), whether is PeTar kicking Fi or the other way around, and all the physical parameters of the system. 
When trying with less than 15000 sph particles the code works without errors.

here's the error with redirection='none' on petar when running with 5*10**4 sph particles and a cluster of 200 stars
```
Fi is synchronizing .. done
PETAR: recommit_particles start
PETAR: recommit_particles end
petar_worker: src/PeTar/src/soft_force.hpp:273: void CalcForcePPSimd<Tpi, Tpj>::operator()(const Tpi*, ParticleSimulator::S32, const Tpj*, ParticleSimulator::S32, ForceSoft*) [with Tpi = ParticleBase; Tpj = FPSoft; ParticleSimulator::S32 = int]: Assertion `n_ip<=pg.NIMAX' failed.
ni= 48793 NIMAX= 16384 nj= 200 NJMAX= 131072
Fi receives kick from petar --------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode -1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/paul/Scrivania/Amuse-env/lib/python3.8/site-packages/amuse/rfi/core.py", line 120, in __call__
    dtype_to_result = self.interface.channel.recv_message(call_id, self.specification.id, handle_as_array)
  File `"/home/paul/Scrivania/Amuse-env/lib/python3.8/site-packages/amuse/rfi/channel.py",` line 1164, in recv_message
    raise exceptions.CodeException("Error in code: " + error_message)
amuse.support.exceptions.CodeException: Error in code: no error message - code probably died, sorry.
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "My_first_issue.py", line 108, in <module>
    system_gr_hyd.evolve_model(SysTime,timestep=timestep_gr_hyd)
  File "/home/paul/Scrivania/Amuse-env/lib/python3.8/site-packages/amuse/ext/bridge.py", line 152, in evolve_model
    return self.evolve_joined_leapfrog(tend,timestep)
  File "/home/paul/Scrivania/Amuse-env/lib/python3.8/site-packages/amuse/ext/bridge.py", line 170, in evolve_joined_leapfrog
    self.kick_systems(timestep/2)
  File "/home/paul/Scrivania/Amuse-env/lib/python3.8/site-packages/amuse/ext/bridge.py", line 295, in kick_systems
    kick_system(x,y.get_gravity_at_point,dt)
  File "/home/paul/Scrivania/Amuse-env/lib/python3.8/site-packages/amuse/ext/bridge.py", line 101, in kick_system
    ax,ay,az=get_gravity(parts.radius,parts.x,parts.y,parts.z)
  File "/home/paul/Scrivania/Amuse-env/lib/python3.8/site-packages/amuse/support/methods.py", line 168, in __call__
    result = self.method(*list_arguments, **keyword_arguments)
  File "/home/paul/Scrivania/Amuse-env/lib/python3.8/site-packages/amuse/support/methods.py", line 168, in __call__
    result = self.method(*list_arguments, **keyword_arguments)
  File "/home/paul/Scrivania/Amuse-env/lib/python3.8/site-packages/amuse/support/methods.py", line 168, in __call__
    result = self.method(*list_arguments, **keyword_arguments)
  File "/home/paul/Scrivania/Amuse-env/lib/python3.8/site-packages/amuse/support/methods.py", line 267, in __call__
    return self.method(*list_arguments, **keyword_arguments)
  File "/home/paul/Scrivania/Amuse-env/lib/python3.8/site-packages/amuse/rfi/core.py", line 123, in __call__
    raise exceptions.CodeException("Exception when calling function '{0}', of code '{1}', exception was '{2}'".format(self.specification.name, type(self.interface).__name__, ex))
amuse.support.exceptions.CodeException: Exception when calling function 'get_gravity_at_point', of code 'petarInterface', exception was 'Error in code: no error message - code probably died, sorry.'

```
Is there a way to get around the problem?

I am running on Ubuntu 20.04.1 LTS, Pyhon 3.8.5, Numpy 1.19.4, AMUSE 13.2.0

**Comment by rieder** [comment]
As a workaround (but also recommended practice), you could use an external code to do the kicking instead of Petar. Since you're kicking a tree code, this wouldn't really degrade your accuracy (and it will be faster). 
You would set it up like this:

```python
from amuse.couple.bridge import (
    Bridge, CalculateFieldForCodes,
)

def new_field_kicker(code):
    kicker = Fi(converter, mode="openmp")
    kicker.parameters.epsilon_squared = epsilon_squared
    result = CalculateFieldForCodes(
        new_field_gravity_code,
        [code],
    )
    return result

to_sph_kickers = [
    new_field_code(nbody_code),
]
to_nbody_kickers = [
    new_field_code(sph_code),
]

system = Bridge(
    timestep=timestep_bridge,
)
system.add_system(
    nbody_code,
    partners=to_nbody_kickers,
    do_sync=True,
)
system.add_system(
    sph_code,
    partners=to_sph_kickers,
    do_sync=True,
    h_smooth_is_eps=True,
)
```

**Comment by PaoloSuin** [comment]
Thank you so much for your reply
I tried to reproduce your snippet assuming new_field_code = new_field_kicker, but when to_nbody_kickers tries to kick the nbody code, bridge returns that this error: 

```
petar receives kick from CalculateFieldForCodes Traceback (most recent call last):
   system_gr_hyd.evolve_model(SysTime)
  File "/home/paul/Scrivania/Amuse-env/lib/python3.8/site-packages/amuse/couple/bridge.py", line 556, in evolve_model
    return self.evolve_joined_leapfrog(tend,timestep)
  File "/home/paul/Scrivania/Amuse-env/lib/python3.8/site-packages/amuse/couple/bridge.py", line 571, in evolve_joined_leapfrog
    self.kick_codes(timestep/2.)
  File "/home/paul/Scrivania/Amuse-env/lib/python3.8/site-packages/amuse/couple/bridge.py", line 712, in kick_codes
    de += x.kick(dt)
  File "/home/paul/Scrivania/Amuse-env/lib/python3.8/site-packages/amuse/couple/bridge.py", line 455, in kick
    self.kick_with_field_code(
  File "/home/paul/Scrivania/Amuse-env/lib/python3.8/site-packages/amuse/couple/bridge.py", line 491, in kick_with_field_code
    ax,ay,az=field_code.get_gravity_at_point(
  File "/home/paul/Scrivania/Amuse-env/lib/python3.8/site-packages/amuse/couple/bridge.py", line 137, in get_gravity_at_point
    code = self._setup_code()
  File "/home/paul/Scrivania/Amuse-env/lib/python3.8/site-packages/amuse/couple/bridge.py", line 166, in _setup_code
    return self.code_factory_function()
TypeError: 'Fi' object is not callable

```
