### ISSUE TITLE
netCFD fails to build

### ISSUE THREAD

**Issue by orbitfold** [amusecode/amuse#72]
I'm trying to build AMUSE on Linux cluster at LRZ, following the build procedure (http://amusecode.org/doc/install/howto-install-prerequisites.html#installation-scripts) results in the following error:

```
configure: error: Can't find or link to the hdf5 library. Use --disable-netcdf-4, or see config.log for errors.
Traceback (most recent call last):
  File "./install.py", line 750, in <module>
    _commands[x](names, skip)
  File "./install.py", line 675, in install
    INSTALL.build_apps(names, skip)
  File "./install.py", line 544, in build_apps
    function(temp_app_dir)
  File "./install.py", line 341, in basic_build
    self.run_application(x, path)
  File "./install.py", line 228, in run_application
    raise Exception("Error when running <" + commandline + ">")
Exception: Error when running <./configure --prefix=/home/hpc/pr28fa/di73kuj2/amuse/prerequisites --enable-shared>
```

**Comment by orbitfold** [comment]
NetCFD seems to want LIBRARY_PATH and CPATH to be appropriately set. I've added the lines to install documentation.

**Comment by ipelupessy** [comment]
this can be fixed by the above mention env variables, or by adapting the install.py along the lines of build_libraries.py of the binbuild...anyway fixed
