### ISSUE TITLE
Docs fail to build on readthedocs

### ISSUE THREAD

**Issue by rieder** [amusecode/amuse#806]
Currently the docs fail to build, with the following error log.
This should be resolved.
```
Running Sphinx v4.3.0
loading translations [en]... done
making output directory... done
[autosummary] generating autosummary for: design/architecture.rst, design/coupling.rst, design/index.rst, design/introduction.rst, design/mpi.rst, design/packages.rst, design/sets.rst, index.rst, install/configuration.rst, install/documenting.rst, ..., tutorial/c_code.rst, tutorial/fortran_code.rst, tutorial/gravitational_dynamics_code.rst, tutorial/grid_boundary.rst, tutorial/index.rst, tutorial/legacy_code.rst, tutorial/most_massive_from_salpeter.rst, tutorial/particle_sets.rst, tutorial/plot.rst, tutorial/units.rst
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 68 source files that are out of date
updating environment: [new config] 68 added, 0 changed, 0 removed
reading sources... [  1%] design/architecture
reading sources... [  2%] design/coupling
reading sources... [  4%] design/index
reading sources... [  5%] design/introduction
reading sources... [  7%] design/mpi
reading sources... [  8%] design/packages
reading sources... [ 10%] design/sets
reading sources... [ 11%] index
reading sources... [ 13%] install/configuration
reading sources... [ 14%] install/documenting
reading sources... [ 16%] install/getting-started
reading sources... [ 17%] install/howto-install-AMUSE
reading sources... [ 19%] install/howto-install-prerequisites
reading sources... [ 20%] install/howto-obtain-AMUSE
reading sources... [ 22%] install/index
reading sources... [ 23%] install/install-macos-highsierra-virtualenv-python2
reading sources... [ 25%] install/install-macos-highsierra-virtualenv-python3
reading sources... [ 26%] install/install-prerequisites-arch
reading sources... [ 27%] install/install-prerequisites-centos
reading sources... [ 29%] install/install-prerequisites-fedora
reading sources... [ 30%] install/install-prerequisites-osx
reading sources... [ 32%] install/install-prerequisites-suse
reading sources... [ 33%] install/install-prerequisites-ubuntu
reading sources... [ 35%] install/install-ubuntu-1804-virtualenv-python2
reading sources... [ 36%] install/install-ubuntu-1804-virtualenv-python3
reading sources... [ 38%] interactive_tutorial/index
reading sources... [ 39%] reference/available-codes
/home/docs/checkouts/readthedocs.org/user_builds/amuse/checkouts/latest/doc/index.rst:20: WARNING: Unknown directive type "htmlonly".

.. htmlonly::
   - `Examples <examples/index.html>`_
/home/docs/checkouts/readthedocs.org/user_builds/amuse/checkouts/latest/doc/interactive_tutorial/index.rst:37: WARNING: toctree contains reference to nonexisting document 'interactive_tutorial/01-Loading_AMUSE'
/home/docs/checkouts/readthedocs.org/user_builds/amuse/checkouts/latest/doc/interactive_tutorial/index.rst:37: WARNING: toctree contains reference to nonexisting document 'interactive_tutorial/02-Quantities_with_units'
/home/docs/checkouts/readthedocs.org/user_builds/amuse/checkouts/latest/doc/interactive_tutorial/index.rst:37: WARNING: toctree contains reference to nonexisting document 'interactive_tutorial/03-Generic_units'
/home/docs/checkouts/readthedocs.org/user_builds/amuse/checkouts/latest/doc/interactive_tutorial/index.rst:37: WARNING: toctree contains reference to nonexisting document 'interactive_tutorial/04-Collections_of_Particles'
/home/docs/checkouts/readthedocs.org/user_builds/amuse/checkouts/latest/doc/interactive_tutorial/index.rst:37: WARNING: toctree contains reference to nonexisting document 'interactive_tutorial/05-Attributes_and_functions_on_particle_collections'
/home/docs/checkouts/readthedocs.org/user_builds/amuse/checkouts/latest/doc/interactive_tutorial/index.rst:37: WARNING: toctree contains reference to nonexisting document 'interactive_tutorial/06-Using_a_community_code'
/home/docs/checkouts/readthedocs.org/user_builds/amuse/checkouts/latest/doc/interactive_tutorial/index.rst:37: WARNING: toctree contains reference to nonexisting document 'interactive_tutorial/07-Channels'
/home/docs/checkouts/readthedocs.org/user_builds/amuse/checkouts/latest/doc/interactive_tutorial/index.rst:37: WARNING: toctree contains reference to nonexisting document 'interactive_tutorial/08-Grids'

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 344, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 296, in build_update
    len(to_build))
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 308, in build
    updated_docnames = set(self.read())
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 415, in read
    self._read_serial(docnames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 436, in _read_serial
    self.read_doc(docname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 476, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/sphinx/io.py", line 189, in read_doc
    pub.publish()
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/core.py", line 218, in publish
    self.settings)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/sphinx/io.py", line 109, in read
    self.parse()
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/readers/__init__.py", line 77, in parse
    self.parser.parse(self.input, document)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/sphinx/parsers.py", line 101, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 171, in run
    input_source=document['source'])
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/statemachine.py", line 242, in run
    context, state, transitions)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/statemachine.py", line 459, in check_line
    return method(match, context, next_state)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 3005, in text
    self.section(title.lstrip(), source, style, lineno + 1, messages)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/statemachine.py", line 242, in run
    context, state, transitions)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/statemachine.py", line 459, in check_line
    return method(match, context, next_state)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2769, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/statemachine.py", line 242, in run
    context, state, transitions)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/statemachine.py", line 459, in check_line
    return method(match, context, next_state)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2769, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/statemachine.py", line 242, in run
    context, state, transitions)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/statemachine.py", line 459, in check_line
    return method(match, context, next_state)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2769, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/statemachine.py", line 242, in run
    context, state, transitions)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/statemachine.py", line 459, in check_line
    return method(match, context, next_state)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2769, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/statemachine.py", line 242, in run
    context, state, transitions)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/statemachine.py", line 459, in check_line
    return method(match, context, next_state)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2342, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2354, in explicit_construct
    return method(self, expmatch)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2097, in directive
    directive_class, match, type_name, option_presets)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2146, in run_directive
    result = directive_instance.run()
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/sphinx/ext/autodoc/directive.py", line 173, in run
    result = parse_generated_content(self.state, params.result, documenter)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/sphinx/ext/autodoc/directive.py", line 116, in parse_generated_content
    nested_parse_with_titles(state, content, node)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/sphinx/util/nodes.py", line 335, in nested_parse_with_titles
    return state.nested_parse(content, 0, node, match_titles=1)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/statemachine.py", line 242, in run
    context, state, transitions)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/statemachine.py", line 459, in check_line
    return method(match, context, next_state)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2344, in explicit_markup
    self.explicit_list(blank_finish)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2374, in explicit_list
    match_titles=self.state_machine.match_titles)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 319, in nested_list_parse
    node=node, match_titles=match_titles)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/statemachine.py", line 242, in run
    context, state, transitions)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/statemachine.py", line 459, in check_line
    return method(match, context, next_state)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2647, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2354, in explicit_construct
    return method(self, expmatch)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2097, in directive
    directive_class, match, type_name, option_presets)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2146, in run_directive
    result = directive_instance.run()
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/sphinx/ext/autodoc/directive.py", line 173, in run
    result = parse_generated_content(self.state, params.result, documenter)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/sphinx/ext/autodoc/directive.py", line 120, in parse_generated_content
    state.nested_parse(content, 0, node)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/statemachine.py", line 242, in run
    context, state, transitions)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/statemachine.py", line 459, in check_line
    return method(match, context, next_state)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2342, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2354, in explicit_construct
    return method(self, expmatch)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2097, in directive
    directive_class, match, type_name, option_presets)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2146, in run_directive
    result = directive_instance.run()
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/sphinx/domains/__init__.py", line 286, in run
    return super().run()
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/sphinx/directives/__init__.py", line 208, in run
    self.state.nested_parse(self.content, self.content_offset, contentnode)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/statemachine.py", line 242, in run
    context, state, transitions)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/statemachine.py", line 459, in check_line
    return method(match, context, next_state)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2342, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2354, in explicit_construct
    return method(self, expmatch)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2097, in directive
    directive_class, match, type_name, option_presets)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2146, in run_directive
    result = directive_instance.run()
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/sphinx/ext/autodoc/directive.py", line 162, in run
    documenter.generate(more_content=self.content)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/envs/latest/lib/python3.7/site-packages/sphinx/ext/autodoc/__init__.py", line 913, in generate
    if not self.import_object():
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/checkouts/latest/doc/sphinxext/autodoc_parameters.py", line 90, in import_object
    self._datadescriptor = False
AttributeError: can't set attribute

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/amuse/checkouts/latest/doc/sphinxext/autodoc_parameters.py", line 90, in import_object
    self._datadescriptor = False
AttributeError: can't set attribute
The full traceback has been saved in /tmp/sphinx-err-l3f6tody.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!


Thank you for using AMUSE!
In this session you have used the modules below. Please cite any relevant articles:


	"AMUSE (unknown version)"
		https://doi.org/10.5281/zenodo.4946130
		[2018araa.book.....P] Portegies Zwart, S. & McMillan, S.L.W., 2018
		[2013CoPhC.183..456P] ** Portegies Zwart, S. et al., 2013
		[2013A&A...557A..84P] ** Pelupessy, F. I. et al., 2013
		[2009NewA...14..369P] Portegies Zwart, S. et al., 2009
```

**Comment by ipelupessy** [comment]
it seems _datadescriptor has turned into  property (w/o setter); its deprecated anyway.. maybe the offending line can just  be removed...
