### ISSUE TITLE
Problem with AMUSE Development install

### ISSUE THREAD

**Issue by tangtong98** [amusecode/amuse#829]
Hello，

 I had no trouble installing AMUSE, but I had a problem with AMUSE Development.  I got an error when running "test_HRdiagram_cluster.py":No module named 'amuse.community.mesa'.  Then I tried to run `pip install -e .` and got the following error:
```
(Amuse-env) tangt@DESKTOP-D7M2799:/mnt/f/amuse-main$ pip install -e .
Obtaining file:///mnt/f/amuse-main
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [36 lines of output]
      Traceback (most recent call last):
        File "/home/tangt/Amuse-env/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/home/tangt/Amuse-env/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/tangt/Amuse-env/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/tmp/pip-build-env-63uiw_nu/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 188, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/tmp/pip-build-env-63uiw_nu/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 281, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/tmp/pip-build-env-63uiw_nu/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 174, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 71, in <module>
          setup(
        File "/tmp/pip-build-env-63uiw_nu/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 155, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-63uiw_nu/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 109, in setup
          _setup_distribution = dist = klass(attrs)
        File "/tmp/pip-build-env-63uiw_nu/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 458, in __init__          _Distribution.__init__(
        File "/tmp/pip-build-env-63uiw_nu/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 293, in __init__
          self.finalize_options()
        File "/tmp/pip-build-env-63uiw_nu/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 851, in finalize_options
          ep(self)
        File "/tmp/pip-build-env-63uiw_nu/overlay/lib/python3.8/site-packages/setuptools_scm/integration.py", line 104, in infer_version
          _assign_version(dist, config)
        File "/tmp/pip-build-env-63uiw_nu/overlay/lib/python3.8/site-packages/setuptools_scm/integration.py", line 51, in _assign_version
          _version_missing(config)
        File "/tmp/pip-build-env-63uiw_nu/overlay/lib/python3.8/site-packages/setuptools_scm/__init__.py", line 106, in _version_missing
          raise LookupError(
      LookupError: setuptools-scm was unable to detect version for /mnt/f/amuse-main.

      Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

      For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
So how can I solve this problen, thank you an advance for your answer.

**Comment by spzwart** [comment]
Dear Tangtong,

In your installation you did not install MESA properly. This package has
to be installed separately. At the moment we have two versions of MESA
in AMUSE, one is a somewhat older (but better tested) version, and the
other has just been adapted to be used with AMUSE. you can install
either of them via a separate download.
Steven, can you tell Tantong what is the current best procedure to
install MESA, because that is not yet reported in the book.

Cheers,
Simon

**Comment by MJCWilhelm** [comment]
I think this may be another error. Did you git clone the amuse repository, or download it from github? I saw a similar error when someone downloaded it, in that case you don't get all of the git infrastructure and amuse seems to require that. So in the place where you want amuse you should do `git clone https://github.com/amusecode/amuse.git`

Concerning MESA, it's not installed by default, because it's such a big package it needs to be downloaded separately. After installing amuse via pip, and building the framework and codes, you should also do `make mesa.code DOWNLOAD_CODES=1`

And about the new version Simon mentioned, the version currently in amuse is an older version of MESA, and an interface to the modern version has been developed but not yet implemented in the main branch. The example script will definitely have been written with the old version in mind, and may not work with the new version. For completeness, the new version is available on the interface developer's amuse fork, https://github.com/rjfarmer/amuse/tree/mesa_15140 (note the branch used).

**Comment by rieder** [comment]
Could you post the output of `pip list | grep amuse`?

**Comment by tangtong98** [comment]
I run `pip list | grep amuse`, get the following results:
```
(Amuse-env) tangt@DESKTOP-D7M2799:~$ pip list | grep amuse
amuse                 2021.7.0.3.dev187+g299457310 /home/tangt/amuse/src
amuse-athena          2021.7.0.2
amuse-bhtree          2021.7.0.2
amuse-bse             2021.7.0.2
amuse-capreole        2021.7.0.2
amuse-evtwin          2021.7.0.2
amuse-fastkick        2021.7.0.2
amuse-fi              2021.7.0.2
amuse-fractalcluster  2021.7.0.2
amuse-framework       2021.7.0.2
amuse-gadget2         2021.7.0.2
amuse-galactics       2021.7.0.2
amuse-galaxia         2021.7.0.2
amuse-halogen         2021.7.0.2
amuse-hermite         2021.7.0.2
amuse-hop             2021.7.0.2
amuse-huayno          2021.7.0.2
amuse-kepler          2021.7.0.2
amuse-kepler-orbiters 2021.7.0.2
amuse-mameclot        2021.7.0.2
amuse-mercury         2021.7.0.2
amuse-mmams           2021.7.0.2
amuse-ph4             2021.7.0.2
amuse-phigrape        2021.7.0.2
amuse-seba            2021.7.0.2
amuse-secularmultiple 2021.7.0.2
amuse-simplex         2021.7.0.2
amuse-smalln          2021.7.0.2
amuse-sphray          2021.7.0.2
amuse-sse             2021.7.0.2
amuse-tests           2021.7.0.2
amuse-twobody         2021.7.0.2
```

**Comment by rieder** [comment]
Thanks.

You will need to uninstall all amuse packages *except* for amuse itself - it should work then.

**Comment by tangtong98** [comment]
Thank you very much for your help, I have been able to use it smoothly.
