### ISSUE TITLE
Installation Failed: "'.' is not recognized as an internal or external command"

### ISSUE THREAD

**Issue by MariosGkMeng** [amusecode/amuse#891]
**Describe the bug**
I am **not** able to install amuse. I get a very peruliar error.

**To Reproduce**
pip install amuse-phantom
OR
pip install amuse-framework
OR
pip install amuse

**Logs**

⚠ The strange error is: 
`        '.' is not recognized as an internal or external command,
`
Is this a typo inside some script? Perhaps after a change in the code?

```
Collecting amuse-phantom
  Using cached amuse-phantom-2022.10.0.tar.gz (25 kB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [143 lines of output]
      Collecting setuptools
        Using cached setuptools-65.4.1-py3-none-any.whl (1.2 MB)
      Collecting wheel
        Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
      Collecting amuse-framework
        Using cached amuse-framework-2022.10.0.tar.gz (656 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'        
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'  
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'  
      Collecting pip>=19.0.0
        Using cached pip-22.2.2-py3-none-any.whl (2.0 MB)
      Collecting pytest>=4.0
        Using cached pytest-7.1.3-py3-none-any.whl (298 kB)
      Collecting numpy>=1.2.2
        Using cached numpy-1.23.4-cp310-cp310-win_amd64.whl (14.6 MB)
      Collecting docutils>=0.6
        Using cached docutils-0.19-py3-none-any.whl (570 kB)
      Collecting h5py>=1.1.0
        Using cached h5py-3.7.0-cp310-cp310-win_amd64.whl (2.6 MB)
      Collecting setuptools-scm
        Using cached setuptools_scm-7.0.5-py3-none-any.whl (42 kB)
      Collecting packaging
        Using cached packaging-21.3-py3-none-any.whl (40 kB)
      Collecting attrs>=19.2.0
        Using cached attrs-22.1.0-py2.py3-none-any.whl (58 kB)
      Collecting pluggy<2.0,>=0.12
        Using cached pluggy-1.0.0-py2.py3-none-any.whl (13 kB)
      Collecting iniconfig
        Using cached iniconfig-1.1.1-py2.py3-none-any.whl (5.0 kB)
      Collecting colorama
        Using cached colorama-0.4.5-py2.py3-none-any.whl (16 kB)
      Collecting tomli>=1.0.0
        Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
      Collecting py>=1.8.2
        Using cached py-1.11.0-py2.py3-none-any.whl (98 kB)
      Collecting typing-extensions
        Using cached typing_extensions-4.4.0-py3-none-any.whl (26 kB)
      Collecting pyparsing!=3.0.5,>=2.0.2
        Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
      Building wheels for collected packages: amuse-framework
        Building wheel for amuse-framework (pyproject.toml): started
        Building wheel for amuse-framework (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error
     
        Building wheel for amuse-framework (pyproject.toml) did not run successfully.
        exit code: 1
     
        [86 lines of output]
        running bdist_wheel
        running build
        C:\Users\username\AppData\Local\Temp\pip-build-env-y_umi2cb\overlay\Lib\site-packages\setuptools\command\build.py:31: SetuptoolsDeprecationWarning:
                    It seems that you are using `distutils.command.build` to add
                    new subcommands. Using `distutils` directly is considered deprecated,
                    please use `setuptools.command.build`.
     
          warnings.warn(msg, SetuptoolsDeprecationWarning)
        running configure_codes
        INFO: get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'
        INFO: customize GnuFCompiler
        WARN: Could not locate executable g77
        WARN: Could not locate executable f77
        INFO: customize IntelVisualFCompiler
        WARN: Could not locate executable ifort
        WARN: Could not locate executable ifl
        INFO: customize AbsoftFCompiler
        WARN: Could not locate executable f90
        INFO: customize CompaqVisualFCompiler
        WARN: Could not locate executable DF
        INFO: customize IntelItaniumVisualFCompiler
        WARN: Could not locate executable efl
        INFO: customize Gnu95FCompiler
        INFO: Found executable C:\Users\username\gcc\bin\gfortran.exe
        Running configure for AMUSE
        error in call, tail output:
     
        '.' is not recognized as an internal or external command,
     
        operable program or batch file.
     
     
        --------------------------------------------------------------------------------
        config.mk not generated; output of configure:
        '.' is not recognized as an internal or external command,
     
        operable program or batch file.
     
     
        Traceback (most recent call last):
          File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\Lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in 
<module>
            main()
          File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\Lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in 
main
            json_out['return_val'] = hook(**hook_input['kwargs'])
          File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\Lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 261, in 
build_wheel
            return _build_backend().build_wheel(wheel_directory, config_settings,
          File "C:\Users\username\AppData\Local\Temp\pip-build-env-y_umi2cb\overlay\Lib\site-packages\setuptools\build_meta.py", line 412, in build_wheel
            return self._build_with_temp_dir(['bdist_wheel'], '.whl',
          File "C:\Users\username\AppData\Local\Temp\pip-build-env-y_umi2cb\overlay\Lib\site-packages\setuptools\build_meta.py", line 397, in _build_with_temp_dir
            self.run_setup()
          File "C:\Users\username\AppData\Local\Temp\pip-build-env-y_umi2cb\overlay\Lib\site-packages\setuptools\build_meta.py", line 482, in run_setup
            super(_BuildMetaLegacyBackend,
          File "C:\Users\username\AppData\Local\Temp\pip-build-env-y_umi2cb\overlay\Lib\site-packages\setuptools\build_meta.py", line 335, in run_setup
            exec(code, locals())
          File "<string>", line 55, in <module>
          File "C:\Users\username\AppData\Local\Temp\pip-build-env-y_umi2cb\overlay\Lib\site-packages\setuptools\__init__.py", line 87, in setup
            return distutils.core.setup(**attrs)
          File "C:\Users\username\AppData\Local\Temp\pip-build-env-y_umi2cb\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
            return run_commands(dist)
          File "C:\Users\username\AppData\Local\Temp\pip-build-env-y_umi2cb\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
            dist.run_commands()
          File "C:\Users\username\AppData\Local\Temp\pip-build-env-y_umi2cb\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 968, in run_commands
            self.run_command(cmd)
          File "C:\Users\username\AppData\Local\Temp\pip-build-env-y_umi2cb\overlay\Lib\site-packages\setuptools\dist.py", line 1217, in run_command
            super().run_command(command)
          File "C:\Users\username\AppData\Local\Temp\pip-build-env-y_umi2cb\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
            cmd_obj.run()
          File "C:\Users\username\AppData\Local\Temp\pip-build-env-y_umi2cb\overlay\Lib\site-packages\wheel\bdist_wheel.py", line 299, in run
            self.run_command('build')
          File "C:\Users\username\AppData\Local\Temp\pip-build-env-y_umi2cb\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
            self.distribution.run_command(command)
          File "C:\Users\username\AppData\Local\Temp\pip-build-env-y_umi2cb\overlay\Lib\site-packages\setuptools\dist.py", line 1217, in run_command
            super().run_command(command)
          File "C:\Users\username\AppData\Local\Temp\pip-build-env-y_umi2cb\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
            cmd_obj.run()
          File "C:\Users\username\AppData\Local\Temp\pip-build-env-y_umi2cb\overlay\Lib\site-packages\setuptools\_distutils\command\build.py", line 132, in run
            self.run_command(cmd_name)
          File "C:\Users\username\AppData\Local\Temp\pip-build-env-y_umi2cb\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
            self.distribution.run_command(command)
          File "C:\Users\username\AppData\Local\Temp\pip-build-env-y_umi2cb\overlay\Lib\site-packages\setuptools\dist.py", line 1217, in run_command
            super().run_command(command)
          File "C:\Users\username\AppData\Local\Temp\pip-build-env-y_umi2cb\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
            cmd_obj.run()
          File "C:\Users\username\AppData\Local\Temp\pip-install-gdxcgdeb\amuse-framework_7697e922db1b4228a194056af8350983\support\setup_codes.py", line 1160, in run
            raise Exception("configure failed")
        Exception: configure failed
        [end of output]

```

**Environment (please complete the following information):**
 - OS and version: Windows 10, x64

**Comment by rieder** [comment]
It looks like you are using Windows, this is not supported except through a Linux subsystem (WSL, Multipass or other).

**Comment by MariosGkMeng** [comment]
Thank you for the very swift reply :D 

Indeed, I jumped the gun and did not look at the text below the "pip install ..." command in the README.md
