### ISSUE TITLE
Creating and plotting grid in supernova/hydrodynamics example

### ISSUE THREAD

**Issue by dnrgodilano7** [amusecode/amuse#915]
Hello and good day.
We were trying to run supernova_grid.py and we are having this error on the plot_grid function:

       Grid.create deprecated, use new_regular_grid instead
       Grid.create deprecated, use new_regular_grid instead
       Traceback (most recent call last):
         File "/Users/dnrgodilano7/Documents/AMUSE/trial/supernova/supernova_grid.py", line 190, in <module>
           main(**o.__dict__)
         File "/Users/dnrgodilano7/Documents/AMUSE/trial/supernova/supernova_grid.py", line 77, in main
           run_grid_code(hydro, grid, t_end, dt)
         File "/Users/dnrgodilano7/Documents/AMUSE/trial/supernova/supernova_grid.py", line 153, in run_grid_code
           plot_grid(grid)
         File "/Users/dnrgodilano7/Documents/AMUSE/trial/supernova/supernova_grid.py", line 17, in plot_grid
          rho = grid.rho[:,:,halfway].value_in(units.g/units.cm**3)
         File "/Users/dnrgodilano7/Amuse-env/lib/python3.9/site-packages/amuse/units/quantities.py", line 604, in __getitem__
          return new_quantity(self._number[index], self.unit)
       IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

on another note, is it possible to use supernova_grid.py to the output of molecular_cloud_collapse_with_sinks.py if we detect SN candidates in longer timescales by using the candidate SN output as initial condition to supernova_grid.py?

Thank you.

**Comment by spzwart** [comment]
dear Nico,

I'll have a look at the ..._grid.py function to see what is wrong.
regarding your second question,: I am not sure that that would be the best
solution,  but in principle what you suggest is possible.
i would simply make a contour plot in pyplot, or convert it to an image.

cheers,
Simon

**Comment by dnrgodilano7** [comment]
Ok, thank you for the help and advice Simon!
