### ISSUE TITLE
Decoding error when building amuse-devel

### ISSUE THREAD

**Issue by LeiRoF** [amusecode/amuse#924]
Hi,
I'm trying to install amuse but I got an error on both Ubuntu 22.04 and Windows 11 systems, with repectively python 3.10.6 and 3.10.9.

I'm simply running
```
pip install amuse
```

Here is the logs:
```
Building wheels for collected packages: amuse-devel
  Building wheel for amuse-devel (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for amuse-devel (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [99 lines of output]
      running bdist_wheel
      running build
      C:\Users\vince\AppData\Local\Temp\pip-build-env-kqkusb55\overlay\Lib\site-packages\setuptools\command\build.py:31: SetuptoolsDeprecationWarning:
                  It seems that you are using `distutils.command.build` to add
                  new subcommands. Using `distutils` directly is considered deprecated,
                  please use `setuptools.command.build`.

        warnings.warn(msg, SetuptoolsDeprecationWarning)
      running configure_codes
      INFO: get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'
      INFO: customize GnuFCompiler
      WARN: Could not locate executable g77
      WARN: Could not locate executable f77
      INFO: customize IntelVisualFCompiler
      WARN: Could not locate executable ifort
      WARN: Could not locate executable ifl
      INFO: customize AbsoftFCompiler
      WARN: Could not locate executable f90
      INFO: customize CompaqVisualFCompiler
      WARN: Could not locate executable DF
      INFO: customize IntelItaniumVisualFCompiler
      WARN: Could not locate executable efl
      INFO: customize Gnu95FCompiler
      INFO: Found executable C:\MinGW\bin\gfortran.exe

      Traceback (most recent call last):
        File "C:\Users\vince\AppData\Local\Temp\pip-req-build-ig4x85iv\support\setup_codes.py", line 757, in call
          self.announce(line[:-1].decode("utf-8"), log.DEBUG)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^
      UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 27: invalid start byte

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.496.0_x64__qbz5n2kfra8p0\Lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 351, in <module>
          main()
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.496.0_x64__qbz5n2kfra8p0\Lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.496.0_x64__qbz5n2kfra8p0\Lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 249, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\vince\AppData\Local\Temp\pip-build-env-kqkusb55\overlay\Lib\site-packages\setuptools\build_meta.py", line 413, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\vince\AppData\Local\Temp\pip-build-env-kqkusb55\overlay\Lib\site-packages\setuptools\build_meta.py", line 398, in _build_with_temp_dir
          self.run_setup()
        File "C:\Users\vince\AppData\Local\Temp\pip-build-env-kqkusb55\overlay\Lib\site-packages\setuptools\build_meta.py", line 485, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\vince\AppData\Local\Temp\pip-build-env-kqkusb55\overlay\Lib\site-packages\setuptools\build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 75, in <module>
        File "C:\Users\vince\AppData\Local\Temp\pip-build-env-kqkusb55\overlay\Lib\site-packages\setuptools\__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\vince\AppData\Local\Temp\pip-build-env-kqkusb55\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\vince\AppData\Local\Temp\pip-build-env-kqkusb55\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\vince\AppData\Local\Temp\pip-build-env-kqkusb55\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\vince\AppData\Local\Temp\pip-build-env-kqkusb55\overlay\Lib\site-packages\setuptools\dist.py", line 1213, in run_command
          super().run_command(command)
        File "C:\Users\vince\AppData\Local\Temp\pip-build-env-kqkusb55\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\vince\AppData\Local\Temp\pip-build-env-kqkusb55\overlay\Lib\site-packages\wheel\bdist_wheel.py", line 325, in run
          self.run_command("build")
        File "C:\Users\vince\AppData\Local\Temp\pip-build-env-kqkusb55\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\vince\AppData\Local\Temp\pip-build-env-kqkusb55\overlay\Lib\site-packages\setuptools\dist.py", line 1213, in run_command
          super().run_command(command)
        File "C:\Users\vince\AppData\Local\Temp\pip-build-env-kqkusb55\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\vince\AppData\Local\Temp\pip-build-env-kqkusb55\overlay\Lib\site-packages\setuptools\_distutils\command\build.py", line 132, in run
          self.run_command(cmd_name)
        File "C:\Users\vince\AppData\Local\Temp\pip-build-env-kqkusb55\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\vince\AppData\Local\Temp\pip-build-env-kqkusb55\overlay\Lib\site-packages\setuptools\dist.py", line 1213, in run_command
          super().run_command(command)
        File "C:\Users\vince\AppData\Local\Temp\pip-build-env-kqkusb55\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\vince\AppData\Local\Temp\pip-req-build-ig4x85iv\support\setup_codes.py", line 1163, in run
          result,content=self.call(['./configure'], env=environment, shell=True)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\vince\AppData\Local\Temp\pip-req-build-ig4x85iv\support\setup_codes.py", line 761, in call
          line.replace(0x82,0x80)
      TypeError: a bytes-like object is required, not 'int'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for amuse-devel
Failed to build amuse-devel
ERROR: Could not build wheels for amuse-devel, which is required to install pyproject.toml-based projects
```

Here is the line where the error occure:
https://github.com/amusecode/amuse/blob/cbec986150fbf0bf744caa236e6a42831f9a4e8a/support/setup_codes.py#L756

**Comment by rieder** [comment]
Hi,

This looks like the error you get installing on Windows - this is not supported.
We can probably help with the Ubuntu error, but the log for that is not included here.

**Comment by rieder** [comment]
Looks like you are missing some prerequisite libraries (fftw, gsl and hdf5).
Also, I would recommend installing amuse-framework and then the inidividual packages you will be using rather than installing amuse in one go.

**Comment by rieder** [comment]
```
sudo apt-get install build-essential gfortran python3-dev \
  libopenmpi-dev openmpi-bin \
  libgsl-dev cmake libfftw3-3 libfftw3-dev \
  libgmp3-dev libmpfr6 libmpfr-dev \
  libhdf5-serial-dev hdf5-tools \
  libblas-dev liblapack-dev \
  python3-venv python3-pip git
```
Please make sure you do this before installing AMUSE via pip on ubuntu (https://amuse.readthedocs.io/en/latest/install/howto-install-AMUSE.html)

**Comment by LeiRoF** [comment]
That's weird because I already installed everything, as the screenshot below can attest:

![image](https://user-images.githubusercontent.com/12165342/216357348-bd712079-dde9-49b5-9e29-f12dfe3ac21a.png)

**Comment by rieder** [comment]
Then can you try clearing your pip cache, or re-installing amuse-framework with `pip install amuse-framework --no-cache-dir`?
It may have been configured before you installed these, in which case the cached build is wrong.

**Comment by LeiRoF** [comment]
Ok, it worked, thanks you very much for your help!
