### ISSUE TITLE
Endless building wheel for amuse-mesa

### ISSUE THREAD

**Issue by DimitriiTrater** [amusecode/amuse#949]
I just wanted to install amuse-mesa
But after 30 minutes, I realized that something was wrong here
What do I need to do to make it work?
```
Collecting amuse-mesa
  Using cached amuse-mesa-2023.4.0.tar.gz (59 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: amuse-framework in ./amuse-env/lib/python3.10/site-packages (from amuse-mesa) (2023.4.0)
Collecting amuse-mesa-r15140 (from amuse-mesa)
  Using cached amuse-mesa-r15140-2023.4.0.tar.gz (58 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: setuptools>=41.0.0 in ./amuse-env/lib/python3.10/site-packages (from amuse-framework->amuse-mesa) (59.6.0)
Requirement already satisfied: setuptools-scm in ./amuse-env/lib/python3.10/site-packages (from amuse-framework->amuse-mesa) (7.1.0)
Requirement already satisfied: pip>=19.0.0 in ./amuse-env/lib/python3.10/site-packages (from amuse-framework->amuse-mesa) (23.1)
Requirement already satisfied: wheel>=0.32 in ./amuse-env/lib/python3.10/site-packages (from amuse-framework->amuse-mesa) (0.40.0)
Requirement already satisfied: docutils>=0.6 in ./amuse-env/lib/python3.10/site-packages (from amuse-framework->amuse-mesa) (0.19)
Requirement already satisfied: numpy>=1.2.2 in ./amuse-env/lib/python3.10/site-packages (from amuse-framework->amuse-mesa) (1.24.2)
Requirement already satisfied: pytest>=4.0 in ./amuse-env/lib/python3.10/site-packages (from amuse-framework->amuse-mesa) (7.3.1)
Requirement already satisfied: h5py>=1.1.0 in ./amuse-env/lib/python3.10/site-packages (from amuse-framework->amuse-mesa) (3.8.0)
Requirement already satisfied: iniconfig in ./amuse-env/lib/python3.10/site-packages (from pytest>=4.0->amuse-framework->amuse-mesa) (2.0.0)
Requirement already satisfied: packaging in ./amuse-env/lib/python3.10/site-packages (from pytest>=4.0->amuse-framework->amuse-mesa) (23.1)
Requirement already satisfied: pluggy<2.0,>=0.12 in ./amuse-env/lib/python3.10/site-packages (from pytest>=4.0->amuse-framework->amuse-mesa) (1.0.0)
Requirement already satisfied: exceptiongroup>=1.0.0rc8 in ./amuse-env/lib/python3.10/site-packages (from pytest>=4.0->amuse-framework->amuse-mesa) (1.1.1)
Requirement already satisfied: tomli>=1.0.0 in ./amuse-env/lib/python3.10/site-packages (from pytest>=4.0->amuse-framework->amuse-mesa) (2.0.1)
Requirement already satisfied: typing-extensions in ./amuse-env/lib/python3.10/site-packages (from setuptools-scm->amuse-framework->amuse-mesa) (4.5.0)
Building wheels for collected packages: amuse-mesa, amuse-mesa-r15140
  Building wheel for amuse-mesa (pyproject.toml) ... -
```

**Comment by rieder** [comment]
Hello Dimitri,
Mesa can take a really long time to build, more than half an hour would really not surprise me. Are you sure this was an endless loop?
If so, could you please include the details of your system (OS, cpu etc.)?

**Comment by rieder** [comment]
For now, as a workaround, I would advice to install AMUSE in the developer mode (see https://amuse.readthedocs.io/en/latest/install/howto-install-AMUSE.html#development-build) instead of doing a `pip install amuse-framework amuse-mesa`.
Please make sure you uninstall any already installed AMUSE pip packages before doing so.
Unfortunately I won't have time to further look into this specific issue for the next two weeks.

**Comment by DimitriiTrater** [comment]
Ok, I hope you will answer me in the future.  
Your advice solved my problem - mesa was installed, 
but I tried to install it again through pip and I got an error about which I wrote in one of the comments.
This time I managed to copy it, I quote it below:  

``` sh
$ pip install amuse-mesa                               
Collecting amuse-mesa                                                                                                     
Using cached amuse-mesa-2023.4.0.tar.gz (59 kB)                                                                         
Installing build dependencies ... done                                                                              
Getting requirements to build wheel ... done                                                                            
Preparing metadata (pyproject.toml) ... done                                                                          
Requirement already satisfied: amuse-framework in ./amuse_install_dir/amuse-env/lib/python3.10/site-packages (from amuse-mesa) (2023.4.0)                                                                                                       
Collecting amuse-mesa-r15140 (from amuse-mesa)                                                                        
Using cached amuse-mesa-r15140-2023.4.0.tar.gz (58 kB)                                                                  
Installing build dependencies ... \ done                                                                      
Getting requirements to build wheel ... done                                                                            
Preparing metadata (pyproject.toml) ... done                                                                          
Requirement already satisfied: setuptools>=41.0.0 in ./amuse_install_dir/amuse-env/lib/python3.10/site-packages (from amuse-framework->amuse-mesa) (67.7.1)                                                                                     
Requirement already satisfied: setuptools-scm in ./amuse_install_dir/amuse-env/lib/python3.10/site-packages (from amuse-framework->amuse-mesa) (7.1.0)                                                                                          
Requirement already satisfied: pip>=19.0.0 in ./amuse_install_dir/amuse-env/lib/python3.10/site-packages (from amuse-framework->amuse-mesa) (23.1)                                                                                              
Requirement already satisfied: wheel>=0.32 in ./amuse_install_dir/amuse-env/lib/python3.10/site-packages (from amuse-framework->amuse-mesa) (0.40.0)                                                                                            
Requirement already satisfied: docutils>=0.6 in ./amuse_install_dir/amuse-env/lib/python3.10/site-packages (from amuse-framework->amuse-mesa) (0.19)                                                                                            
Requirement already satisfied: numpy>=1.2.2 in ./amuse_install_dir/amuse-env/lib/python3.10/site-packages (from amuse-framework->amuse-mesa) (1.24.2)                                                                                           
Requirement already satisfied: pytest>=4.0 in ./amuse_install_dir/amuse-env/lib/python3.10/site-packages (from amuse-framework->amuse-mesa) (7.3.1)                                                                                             
Requirement already satisfied: h5py>=1.1.0 in ./amuse_install_dir/amuse-env/lib/python3.10/site-packages (from amuse-framework->amuse-mesa) (3.8.0)                                                                                             
Requirement already satisfied: iniconfig in ./amuse_install_dir/amuse-env/lib/python3.10/site-packages (from pytest>=4.0->amuse-framework->amuse-mesa) (2.0.0)                                                                                  
Requirement already satisfied: packaging in ./amuse_install_dir/amuse-env/lib/python3.10/site-packages (from pytest>=4.0->amuse-framework->amuse-mesa) (23.1)                                                                                   
Requirement already satisfied: pluggy<2.0,>=0.12 in ./amuse_install_dir/amuse-env/lib/python3.10/site-packages (from pytest>=4.0->amuse-framework->amuse-mesa) (1.0.0)                                                                          
Requirement already satisfied: exceptiongroup>=1.0.0rc8 in ./amuse_install_dir/amuse-env/lib/python3.10/site-packages (from pytest>=4.0->amuse-framework->amuse-mesa) (1.1.1)                                                                   
Requirement already satisfied: tomli>=1.0.0 in ./amuse_install_dir/amuse-env/lib/python3.10/site-packages (from pytest>=4.0->amuse-framework->amuse-mesa) (2.0.1)                                                                               
Requirement already satisfied: typing-extensions in ./amuse_install_dir/amuse-env/lib/python3.10/site-packages (from setuptools-scm->amuse-framework->amuse-mesa) (4.5.0)                                                                       
Building wheels for collected packages: amuse-mesa, amuse-mesa-r15140                                                     
Building wheel for amuse-mesa (pyproject.toml) ... error                                                                
error:subprocess-exited-with-error
× Building wheel for amuse-mesa (pyproject.toml) did not run successfully.                                              
│ exit code: 1                                                                                                          
╰─> [218 lines of output]                                                                                                   
running bdist_wheel                                                                                                     
running build                                                                                                           
running build_py                                                                                                        
creating build                                                                                                          
creating build/lib                                                                                                      
creating build/lib/amuse                                                                                                
creating build/lib/amuse/community                                                                                      
creating build/lib/amuse/community/mesa                                                                                 
copying src/amuse/community/mesa/version.py -> build/lib/amuse/community/mesa                                           
copying src/amuse/community/mesa/interface.py -> build/lib/amuse/community/mesa                                         
copying src/amuse/community/mesa/__init__.py -> build/lib/amuse/community/mesa                                          
running build_codes                                                                                                     
building libraries and community codes                                                                                  
build, for logging, see 'build.log'                                                                                     
creating build/temp.linux-x86_64-cpython-310                                                                            
creating build/temp.linux-x86_64-cpython-310/codes                                                                      
creating build/temp.linux-x86_64-cpython-310/codes/mesa_r15140                                                          
copying src/amuse/community/mesa_r15140/patch_files.py -> build/temp.linux-x86_64-cpython-310/codes/mesa_r15140         
creating build/temp.linux-x86_64-cpython-310/codes/mesa_r15140/mesa_reqs                                                
copying src/amuse/community/mesa_r15140/mesa_reqs/README -> build/temp.linux-x86_64-cpython-310/codes/mesa_r15140/mesa_reqs                                                                                                                     
creating build/temp.linux-x86_64-cpython-310/codes/mesa_r15140/examples                                                 
copying src/amuse/community/mesa_r15140/examples/inlist -> build/temp.linux-x86_64-cpython-310/codes/mesa_r15140/examples                                                                                                                       
copying src/amuse/community/mesa_r15140/examples/controls.py -> build/temp.linux-x86_64-cpython-310/codes/mesa_r15140/examples                                                                                                                  
copying src/amuse/community/mesa_r15140/examples/rotation.py -> build/temp.linux-x86_64-cpython-310/codes/mesa_r15140/examples                                                                                                                  
copying src/amuse/community/mesa_r15140/examples/purehe.py -> build/temp.linux-x86_64-cpython-310/codes/mesa_r15140/examples                                                                                                                    
copying src/amuse/community/mesa_r15140/examples/multi.py -> build/temp.linux-x86_64-cpython-310/codes/mesa_r15140/examples                                                                                                                     
copying src/amuse/community/mesa_r15140/examples/prems.py -> build/temp.linux-x86_64-cpython-310/codes/mesa_r15140/examples                                                                                                                     
copying src/amuse/community/mesa_r15140/examples/gyre.in -> build/temp.linux-x86_64-cpython-310/codes/mesa_r15140/examples                                                                                                                      
copying src/amuse/community/mesa_r15140/examples/basic2.py -> build/temp.linux-x86_64-cpython-310/codes/mesa_r15140/examples                                                                                                                    
copying src/amuse/community/mesa_r15140/examples/basic.py -> build/temp.linux-x86_64-cpython-310/codes/mesa_r15140/examples                                                                                                                     
copying src/amuse/community/mesa_r15140/examples/new_model.py -> build/temp.linux-x86_64-cpython-310/codes/mesa_r15140/examples                                                                                                                 
copying src/amuse/community/mesa_r15140/examples/sun.py -> build/temp.linux-x86_64-cpython-310/codes/mesa_r15140/examples                                                                                                                       
copying src/amuse/community/mesa_r15140/examples/gyre.py -> build/temp.linux-x86_64-cpython-310/codes/mesa_r15140/examples                                                                                                                      
copying src/amuse/community/mesa_r15140/examples/plot.py -> build/temp.linux-x86_64-cpython-310/codes/mesa_r15140/examples                                                                                                                      
copying src/amuse/community/mesa_r15140/examples/inlist.py -> build/temp.linux-x86_64-cpython-310/codes/mesa_r15140/examples                                                                                                                    
copying src/amuse/community/mesa_r15140/examples/__init__.py -> build/temp.linux-x86_64-cpython-310/codes/mesa_r15140/examples                                                                                                                  
copying src/amuse/community/mesa_r15140/examples/save_and_load.py -> build/temp.linux-x86_64-cpython-310/codes/mesa_r15140/examples                                                                                                             
copying src/amuse/community/mesa_r15140/Makefile -> build/temp.linux-x86_64-cpython-310/codes/mesa_r15140               
copying src/amuse/community/mesa_r15140/run_star_extras.f90 -> build/temp.linux-x86_64-cpython-310/codes/mesa_r15140                                                                                                                            
copying src/amuse/community/mesa_r15140/mesa_interface.f90 -> build/temp.linux-x86_64-cpython-310/codes/mesa_r15140                                                                                                                             
copying src/amuse/community/mesa_r15140/.gitignore -> build/temp.linux-x86_64-cpython-310/codes/mesa_r15140             creating build/temp.linux-x86_64-cpython-310/codes/mesa_r15140/patches                                                  
copying src/amuse/community/mesa_r15140/patches/0001-Stop-crashes-when-profile-column-name-is-bad.patch -> build/temp.linux-x86_64-cpython-310/codes/mesa_r15140/patches                                                                        
copying src/amuse/community/mesa_r15140/patches/series_deps -> build/temp.linux-x86_64-cpython-310/codes/mesa_r15140/patches                                                                                                                    
copying src/amuse/community/mesa_r15140/patches/0001-Get-photo-loading-working.patch -> build/temp.linux-x86_64-cpython-310/codes/mesa_r15140/patches                                                                                           
copying src/amuse/community/mesa_r15140/patches/fpx3_deps.patch -> build/temp.linux-x86_64-cpython-310/codes/mesa_r15140/patches                                                                                                                
copying src/amuse/community/mesa_r15140/patches/0001-Add-support-for-namelist-setting-from-a-string.patch -> build/temp.linux-x86_64-cpython-310/codes/mesa_r15140/patches                                                                      
copying src/amuse/community/mesa_r15140/patches/0001-Dont-make-empty-output-directories.patch -> build/temp.linux-x86_64-cpython-310/codes/mesa_r15140/patches                                                                                  
copying src/amuse/community/mesa_r15140/patches/makefile_header_non_mesasdk -> build/temp.linux-x86_64-cpython-310/codes/mesa_r15140/patches                                                                                                    
copying src/amuse/community/mesa_r15140/patches/0004-Fix-adipls-and-gyre-builds.patch -> build/temp.linux-x86_64-cpython-310/codes/mesa_r15140/patches                                                                                          
copying src/amuse/community/mesa_r15140/patches/lapack95.patch -> build/temp.linux-x86_64-cpython-310/codes/mesa_r15140/patches                                                                                                                 
copying src/amuse/community/mesa_r15140/patches/0001-Patch-error-messages.patch -> build/temp.linux-x86_64-cpython-310/codes/mesa_r15140/patches                                                                                                
copying src/amuse/community/mesa_r15140/patches/0001-declare-i.patch -> build/temp.linux-x86_64-cpython-310/codes/mesa_r15140/patches                                                                                                           
copying src/amuse/community/mesa_r15140/patches/0003-Add-mpi-to-utils.patch -> build/temp.linux-x86_64-cpython-310/codes/mesa_r15140/patches                                                                                                    
copying src/amuse/community/mesa_r15140/patches/series_mesa -> build/temp.linux-x86_64-cpython-310/codes/mesa_r15140/patches                                                                                                                    
copying src/amuse/community/mesa_r15140/patches/0001-Fix-astero-builds-when-disabled.patch -> build/temp.linux-x86_64-cpython-310/codes/mesa_r15140/patches                                                                                     
copying src/amuse/community/mesa_r15140/interface.f90 -> build/temp.linux-x86_64-cpython-310/codes/mesa_r15140          copying src/amuse/community/mesa_r15140/download.py -> build/temp.linux-x86_64-cpython-310/codes/mesa_r15140            
copying src/amuse/community/mesa_r15140/interface.py -> build/temp.linux-x86_64-cpython-310/codes/mesa_r15140           
[10:43:23] building mesa_r15140       
error in call, tail output:
                                                                                                                                                                                                                      
    inflating: mesa-r15140/adipls/adipack.c/README                                                                          
    inflating: mesa-r15140/adipls/.gitignore                                                                                
    inflating: mesa-r15140/README_mesa_numerics                                                                             
    inflating: mesa-r15140/README                                                                                           
    inflating: mesa-r15140/Doxyfile                                                                                         
    inflating: mesa-r15140/CODEOWNERS                                                                                       
    inflating: mesa-r15140/.readthedocs.yaml                                                                                
    inflating: mesa-r15140/.gitignore                                                                                       
    inflating: mesa-r15140/.editorconfig                                                                                  
    downloading version  from http://www.astro.wisc.edu/~townsend/resource/download/sdk2/src/lapack95.tgz to lapack95.tar.gz                                                                                                                        
    downloading finished                                                                                                    
    unpacking lapack95.tar.gz                                                                                               
    done                                                                                                                    
    downloading version v1.2 from https://github.com/rhdtownsend/crmath/archive/v1.2.zip to v1.2.zip                        
    downloading finished                                                                                                    
    unpacking v1.2.zip                                                                                                      
    done                                                                                                                    
    downloading version 1.0beta4 from http://www.astro.wisc.edu/~townsend/resource/download/sdk2/src/crlibm-1.0beta4.tar.gz to crlibm-1.0beta4.tar.gz                                                                                               
    downloading finished                                                                                                    
    unpacking crlibm-1.0beta4.tar.gz                                                                                        
    done                                                                                                                    
    downloading version  from http://www.astro.wisc.edu/~townsend/resource/download/sdk2/src/fpx3.tar.gz to fpx3.tar.gz                                                                                                                             
    downloading finished                                                                                                    
    unpacking fpx3.tar.gz                                                                                                   
    done                                                                                                                    
    downloading version  from https://raw.githubusercontent.com/rhdtownsend/sdk2/master/profile/common/fpx3/fpx3_deps to fpx3_deps                                                                                                                  
    downloading finished                                                                                                    
    unpacking fpx3_deps                                                                                                     
    done                                                                                                                    
    downloading version 1.12.0 from https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.12/hdf5-1.12.0/src/hdf5-1.12.0.tar.bz2 to hdf-1.12.0.tar.bz2                                                                                              
    downloading finished                                                                                                    
    unpacking hdf-1.12.0.tar.bz2                                                                                            
    done                                                                                                                    
    downloading version 15140 from https://zenodo.org/record/4311514/files/mesa-r15140.zip to mesa-r15140.zip               
    downloading finished                                                                                                    
    unpacking mesa-r15140.zip                                                                                               
    done                                                                                                                    
    make -C . patch                                                                                                         
    make[2]: Entering directory '/tmp/pip-install-iare28f8/amuse-mesa_7f449544f2b448ac80355274c1167a7a/build/temp.linux-x86_64-cpython-310/codes/mesa_r15140'                                                                                       /bin/
    sh: 1: makedepf90: not found                                                                                       
    mkdir -p /tmp/pip-install-iare28f8/amuse-mesa_7f449544f2b448ac80355274c1167a7a/build/temp.linux-x86_64-cpython-310/codes/mesa_r15140/src/mesa-r15140/lib /tmp/pip-install-iare28f8/amuse-mesa_7f449544f2b448ac80355274c1167a7a/build/temp.
    linux-x86_64-cpython-310/codes/mesa_r15140/src/mesa-r15140/include                                                            
    /home/service/amsererer/astrolab_amuse_script/amuse_install_dir/amuse-env/bin/python3 ./patch_files.py                  
    patching file star/private/ctrls_io.f90                                                                                 
    patching file astero/make/makefile_base                                                                                 
    patching file utils/public/utils_lib.f                                                                                  
    patching file adipls/adipack.c/adipls/geninh.d.f                                                                        
    patching file star/public/star_lib.f90                                                                                  
    patching file binary/private/binary_ctrls_io.f90                                                                        
    patching file binary/private/binary_job_ctrls_io.f90                                                                    
    patching file binary/public/binary_lib.f90                                                                              
    patching file eos/private/eos_ctrls_io.f90                                                                              
    patching file eos/public/eos_lib.f90                                                                                    
    patching file kap/private/kap_ctrls_io.f90                                                                              
    patching file kap/public/kap_lib.f90                                                                                    
    patching file star/private/ctrls_io.f90                                                                                 
    patching file star/private/pgstar_ctrls_io.f90                                                                          
    patching file star/private/star_job_ctrls_io.f90                                                                        
    patching file star/public/star_lib.f90                                                                                  
    patching file rates/private/eval_weak.f90                                                                               
    patching file star/job/run_star_support.f90                                                                             
    patching file install                                                                                                   
    patching file fpx3_deps                                                                                                 
    cant find file to patch at input line 3                                                                                
    Perhaps you used the wrong -p or --strip option?                                                                        
    The text leading up to this was:                                                                                        
    --------------------------                                                                                              
    |--- a/LAPACK95/make.inc    2000-11-30 14:18:37.000000000 +0100                                                         
    |+++ b/LAPACK95/make.inc    2021-04-13 11:25:40.895452958 +0200                                                         
    --------------------------                                                                                              
    File to patch:                                                                                                          
    Skip this patch? [y]                                                                                                    
    Skipping patch.                                                                                                         
    2 out of 2 hunks ignored                                                                                                
    checking if quilt is installed ...  no                                                                                  
    applying patches to source code                                                                                         
    0001-Dont-make-empty-output-directories.patch /tmp/pip-install-iare28f8/amuse-mesa_7f449544f2b448ac80355274c1167a7a/build/temp.linux-x86_64-cpython-310/codes/mesa_r15140/patches/0001-Dont-make-empty-output-directories.patch /tmp/pip-install-iare28f8/amuse-mesa_7f449544f2b448ac80355274c1167a7a/build/temp.linux-x86_64-cpython-310/codes/mesa_r15140/src/mesa-r15140                                                                                                                     
    0001-Fix-astero-builds-when-disabled.patch /tmp/pip-install-iare28f8/amuse-mesa_7f449544f2b448ac80355274c1167a7a/build/temp.linux-x86_64-cpython-310/codes/mesa_r15140/patches/0001-Fix-astero-builds-when-disabled.patch /tmp/pip-install-iare28f8/amuse-mesa_7f449544f2b448ac80355274c1167a7a/build/temp.linux-x86_64-cpython-310/codes/mesa_r15140/src/mesa-r15140                                                                                                                           
    0003-Add-mpi-to-utils.patch /tmp/pip-install-iare28f8/amuse-mesa_7f449544f2b448ac80355274c1167a7a/build/temp.linux-x86_64-cpython-310/codes/mesa_r15140/patches/0003-Add-mpi-to-utils.patch /tmp/pip-install-iare28f8/amuse-mesa_7f449544f2b448ac80355274c1167a7a/build/temp.linux-x86_64-cpython-310/codes/mesa_r15140/src/mesa-r15140                                 
    0004-Fix-adipls-and-gyre-builds.patch /tmp/pip-install-iare28f8/amuse-mesa_7f449544f2b448ac80355274c1167a7a/build/temp.linux-x86_64-cpython-310/codes/mesa_r15140/patches/0004-Fix-adipls-and-gyre-builds.patch /tmp/pip-install-iare28f8/amuse-mesa_7f449544f2b448ac80355274c1167a7a/build/temp.linux-x86_64-cpython-310/codes/mesa_r15140/src/mesa-r15140             
    0001-Stop-crashes-when-profile-column-name-is-bad.patch /tmp/pip-install-iare28f8/amuse-mesa_7f449544f2b448ac80355274c1167a7a/build/temp.linux-x86_64-cpython-310/codes/mesa_r15140/patches/0001-Stop-crashes-when-profile-column-name-is-bad.patch /tmp/pip-install-iare28f8/amuse-mesa_7f449544f2b448ac80355274c1167a7a/build/temp.linux-x86_64-cpython-310/codes/mesa_r15140/src/mesa-r15140                                                                                                 
    0001-Add-support-for-namelist-setting-from-a-string.patch /tmp/pip-install-iare28f8/amuse-mesa_7f449544f2b448ac80355274c1167a7a/build/temp.linux-x86_64-cpython-310/codes/mesa_r15140/patches/0001-Add-support-for-namelist-setting-from-a-string.patch /tmp/pip-install-iare28f8/amuse-mesa_7f449544f2b448ac80355274c1167a7a/build/temp.linux-x86_64-cpython-310/codes/mesa_r15140/src/mesa-r15140                                                                                             
    0001-declare-i.patch /tmp/pip-install-iare28f8/amuse-mesa_7f449544f2b448ac80355274c1167a7a/build/temp.linux-x86_64-cpython-310/codes/mesa_r15140/patches/0001-declare-i.patch /tmp/pip-install-iare28f8/amuse-mesa_7f449544f2b448ac80355274c1167a7a/build/temp.linux-x86_64-cpython-310/codes/mesa_r15140/src/mesa-r15140                                               
    0001-Get-photo-loading-working.patch /tmp/pip-install-iare28f8/amuse-mesa_7f449544f2b448ac80355274c1167a7a/build/temp.linux-x86_64-cpython-310/codes/mesa_r15140/patches/0001-Get-photo-loading-working.patch /tmp/pip-install-iare28f8/amuse-mesa_7f449544f2b448ac80355274c1167a7a/build/temp.linux-x86_64-cpython-310/codes/mesa_r15140/src/mesa-r15140               
    0001-Patch-error-messages.patch /tmp/pip-install-iare28f8/amuse-mesa_7f449544f2b448ac80355274c1167a7a/build/temp.linux-x86_64-cpython-310/codes/mesa_r15140/patches/0001-Patch-error-messages.patch /tmp/pip-install-iare28f8/amuse-mesa_7f449544f2b448ac80355274c1167a7a/build/temp.linux-x86_64-cpython-310/codes/mesa_r15140/src/mesa-r15140                         
    Traceback (most recent call last):                                                                                        
    File "/tmp/pip-install-iare28f8/amuse-mesa_7f449544f2b448ac80355274c1167a7a/build/temp.linux-x86_64-cpython-310/codes/mesa_r15140/./patch_files.py", line 121, in <module>                                                                        
    main()                                                                                                                
    File "/tmp/pip-install-iare28f8/amuse-mesa_7f449544f2b448ac80355274c1167a7a/build/temp.linux-x86_64-cpython-310/codes/mesa_r15140/./patch_files.py", line 107, in main                                                                            
    apply_patches_using_patch()                                                                                           
    File "/tmp/pip-install-iare28f8/amuse-mesa_7f449544f2b448ac80355274c1167a7a/build/temp.linux-x86_64-cpython-310/codes/mesa_r15140/./patch_files.py", line 92, in apply_patches_using_patch                                                        
    run_patch(                                                                                                            

        File "/tmp/pip-install-iare28f8/amuse-mesa_7f449544f2b448ac80355274c1167a7a/build/temp.linux-x86_64-cpython-310/codes/mesa_r15140/./patch_files.py", line 73, in run_patch                                                                        
        raise Exception(f"could not apply patch {patchname}")                                                               
        Exception: could not apply patch lapack95.patch                                                                         
        make[2]: *** [Makefile:148: patch] Error 1                                                                              
        make[2]: Leaving directory '/tmp/pip-install-iare28f8/amuse-mesa_7f449544f2b448ac80355274c1167a7a/build/temp.linux-x86_64-cpython-310/codes/mesa_r15140'                                                                                        
        make[1]: *** [Makefile:53: download] Error 2                                                                            
        make[1]: Leaving directory '/tmp/pip-install-iare28f8/amuse-mesa_7f449544f2b448ac80355274c1167a7a/build/temp.linux-x86_64-cpython-310/codes/mesa_r15140'                                                                                        
        make: *** [Makefile:47: /install] Error 2                                                                               
        make: Leaving directory '/tmp/pip-install-iare28f8/amuse-mesa_7f449544f2b448ac80355274c1167a7a/build/temp.linux-x86_64-cpython-310/codes/mesa_r15140'                                                                                                                                                                                                                   
        --------------------------------------------------------------------------------                                        
        will copy worker: src/amuse/community/mesa_r15140                                                                       
        mesa_r15140                                                                                                             
        Community codes not built (because of errors/ missing libraries):                                                       
        ================================================================================                                         
        * mesa_r15140                                                                                                          
        ================================================================================                                        
        0 out of 1 codes built, 0 out of 0 libraries built                                                                      
        Traceback (most recent call last):                                                                                        
        File "/home/service/amsererer/astrolab_amuse_script/amuse_install_dir/amuse-env/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>                                                       
        main()                                                                                                                
        File "/home/service/amsererer/astrolab_amuse_script/amuse_install_dir/amuse-env/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main                                                           
        json_out['return_val'] = hook(**hook_input['kwargs'])                                                                 
        File "/home/service/amsererer/astrolab_amuse_script/amuse_install_dir/amuse-env/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel                                                    
        return _build_backend().build_wheel(wheel_directory, config_settings,                                                 
        File "/tmp/pip-build-env-jepdj8wz/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 416, in build_wheel                                                                                                                        
        return self._build_with_temp_dir(['bdist_wheel'], '.whl',                                                             
        File "/tmp/pip-build-env-jepdj8wz/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 401, in _build_with_temp_dir                                                                                                               
        self.run_setup()                                                                                                      
        File "/tmp/pip-build-env-jepdj8wz/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 487, in run_setup                                                                                                                          
        super(_BuildMetaLegacyBackend,                                                                                        
        File "/tmp/pip-build-env-jepdj8wz/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in run_setup                                                                                                                          
        exec(code, locals())                                                                                                  
        File "<string>", line 50, in <module>                                                                                   
        File "/tmp/pip-build-env-jepdj8wz/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 107, in setup                                                                                                                                
        return distutils.core.setup(**attrs)                                                                                  
        File "/tmp/pip-build-env-jepdj8wz/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup                                                                                                                         
        return run_commands(dist)                                                                                             
        File "/tmp/pip-build-env-jepdj8wz/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands                                                                                                                  
        dist.run_commands()                                                                                                   
        File "/tmp/pip-build-env-jepdj8wz/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands                                                                                                                  
        self.run_command(cmd)                                                                                                 
        File "/tmp/pip-build-env-jepdj8wz/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1244, in run_command                                                                                                                             
        super().run_command(command)                                                                                          
        File "/tmp/pip-build-env-jepdj8wz/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command                                                                                                                   
        cmd_obj.run()                                                                                                         
        File "/tmp/pip-build-env-jepdj8wz/overlay/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 343, in run            
        self.run_command("build")                                                                                             
        File "/tmp/pip-build-env-jepdj8wz/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command                                                                                                                    
        self.distribution.run_command(command)                                                                                
        File "/tmp/pip-build-env-jepdj8wz/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1244, in run_command                                                                                                                             
        super().run_command(command)                                                                                          
        File "/tmp/pip-build-env-jepdj8wz/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command                                                                                                                   
        cmd_obj.run()                                                                                                         
        File "/tmp/pip-build-env-jepdj8wz/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 131, in run                                                                                                                  
        self.run_command(cmd_name)                                                                                            
        File "/tmp/pip-build-env-jepdj8wz/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command                                                                                                                    
        self.distribution.run_command(command)                                                                                
        File "/tmp/pip-build-env-jepdj8wz/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1244, in run_command                                                                                                                             
        super().run_command(command)                                                                                          
        File "/tmp/pip-build-env-jepdj8wz/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command                                                                                                                   
        cmd_obj.run()                                                                                                         
        File "/tmp/pip-install-iare28f8/amuse-mesa_7f449544f2b448ac80355274c1167a7a/support/setup_codes.py", line 1102, in run                                                                                                                            
        raise Exception("No succesful builds detected. Aborting.")                                                          
        Exception: No succesful builds detected. Aborting.                                                                      
        [end of output]                                                                                                                                                                                                                             
        note: This error originates from a subprocess, and is likely not a problem with pip.                                    
        ERROR: Failed building wheel for amuse-mesa

```

**Comment by rieder** [comment]
Should work now (but please bear in mind that downloading and building amuse-mesa can take a long time (30+ minutes) and uses a lot of space (~2+ gigabytes)).

**Comment by rieder** [comment]
Sorry - while MESA now builds, it is still missing some data that is essential to run it. Hoping to fix this soon.
